/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Nov 04 16:04:15 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.rolemanage.people.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T20 table. 
 * You can customize the behavior of this class by editing the class, {@link T20()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT20 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c101 property. */
    private java.lang.String c101;

    /** The value of the simple c102 property. */
    private java.lang.String c102;

    /** The value of the simple c103 property. */
    private java.lang.String c103;

    /** The value of the simple c104 property. */
    private java.lang.String c104;

    /** The value of the simple c108 property. */
    private java.lang.Long c108;

    /** The value of the simple c109 property. */
    private java.lang.Long c109;

    /** The value of the simple c110 property. */
    private java.lang.Long c110;

    /** The value of the simple c119 property. */
    private java.lang.String c119;

    /** The value of the simple c122 property. */
    private java.lang.String c122;

    /** The value of the simple c179 property. */
    private java.lang.String c179;

    /** The value of the simple c490000000 property. */
    private java.lang.String c490000000;

    /** The value of the simple c490000100 property. */
    private java.lang.String c490000100;

    /**
     * Simple constructor of AbstractT20 instances.
     */
    public AbstractT20()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C101 column.
     * @return java.lang.String
     */
    public java.lang.String getC101()
    {
        return this.c101;
    }

    /**
     * Set the value of the C101 column.
     * @param c101
     */
    public void setC101(java.lang.String c101)
    {
        this.c101 = c101;
    }

    /**
     * Return the value of the C102 column.
     * @return java.lang.String
     */
    public java.lang.String getC102()
    {
        return this.c102;
    }

    /**
     * Set the value of the C102 column.
     * @param c102
     */
    public void setC102(java.lang.String c102)
    {
        this.c102 = c102;
    }

    /**
     * Return the value of the C103 column.
     * @return java.lang.String
     */
    public java.lang.String getC103()
    {
        return this.c103;
    }

    /**
     * Set the value of the C103 column.
     * @param c103
     */
    public void setC103(java.lang.String c103)
    {
        this.c103 = c103;
    }

    /**
     * Return the value of the C104 column.
     * @return java.lang.String
     */
    public java.lang.String getC104()
    {
        return this.c104;
    }

    /**
     * Set the value of the C104 column.
     * @param c104
     */
    public void setC104(java.lang.String c104)
    {
        this.c104 = c104;
    }

    /**
     * Return the value of the C108 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC108()
    {
        return this.c108;
    }

    /**
     * Set the value of the C108 column.
     * @param c108
     */
    public void setC108(java.lang.Long c108)
    {
        this.c108 = c108;
    }

    /**
     * Return the value of the C109 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC109()
    {
        return this.c109;
    }

    /**
     * Set the value of the C109 column.
     * @param c109
     */
    public void setC109(java.lang.Long c109)
    {
        this.c109 = c109;
    }

    /**
     * Return the value of the C110 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC110()
    {
        return this.c110;
    }

    /**
     * Set the value of the C110 column.
     * @param c110
     */
    public void setC110(java.lang.Long c110)
    {
        this.c110 = c110;
    }

    /**
     * Return the value of the C119 column.
     * @return java.lang.String
     */
    public java.lang.String getC119()
    {
        return this.c119;
    }

    /**
     * Set the value of the C119 column.
     * @param c119
     */
    public void setC119(java.lang.String c119)
    {
        this.c119 = c119;
    }

    /**
     * Return the value of the C122 column.
     * @return java.lang.String
     */
    public java.lang.String getC122()
    {
        return this.c122;
    }

    /**
     * Set the value of the C122 column.
     * @param c122
     */
    public void setC122(java.lang.String c122)
    {
        this.c122 = c122;
    }

    /**
     * Return the value of the C179 column.
     * @return java.lang.String
     */
    public java.lang.String getC179()
    {
        return this.c179;
    }

    /**
     * Set the value of the C179 column.
     * @param c179
     */
    public void setC179(java.lang.String c179)
    {
        this.c179 = c179;
    }

    /**
     * Return the value of the C490000000 column.
     * @return java.lang.String
     */
    public java.lang.String getC490000000()
    {
        return this.c490000000;
    }

    /**
     * Set the value of the C490000000 column.
     * @param c490000000
     */
    public void setC490000000(java.lang.String c490000000)
    {
        this.c490000000 = c490000000;
    }

    /**
     * Return the value of the C490000100 column.
     * @return java.lang.String
     */
    public java.lang.String getC490000100()
    {
        return this.c490000100;
    }

    /**
     * Set the value of the C490000100 column.
     * @param c490000100
     */
    public void setC490000100(java.lang.String c490000100)
    {
        this.c490000100 = c490000100;
    }
}
