/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Mar 30 12:28:19 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.rolemanage.people.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T223 table. 
 * You can customize the behavior of this class by editing the class, {@link T223()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT223 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c680000001 property. */
    private java.lang.String c680000001;

    /** The value of the simple c680000002 property. */
    private java.lang.String c680000002;

    /** The value of the simple c680000003 property. */
    private java.lang.String c680000003;

    /** The value of the simple c680000004 property. */
    private java.lang.String c680000004;

    /** The value of the simple c680000005 property. */
    private java.lang.String c680000005;

    /** The value of the simple c680000006 property. */
    private java.lang.String c680000006;

    /** The value of the simple c680000007 property. */
    private java.lang.String c680000007;

    /** The value of the simple c680000008 property. */
    private java.lang.String c680000008;

    /** The value of the simple c680000009 property. */
    private java.lang.String c680000009;

    /** The value of the simple c680000010 property. */
    private java.lang.String c680000010;

    /** The value of the simple c680000011 property. */
    private java.lang.String c680000011;

    /** The value of the simple c680000012 property. */
    private java.lang.String c680000012;

    /** The value of the simple c680000013 property. */
    private java.lang.String c680000013;

    /** The value of the simple c680000014 property. */
    private java.lang.String c680000014;

    /** The value of the simple c680000015 property. */
    private java.lang.String c680000015;

    /** The value of the simple c680000016 property. */
    private java.lang.String c680000016;

    /** The value of the simple c680000017 property. */
    private java.lang.String c680000017;

    /** The value of the simple c680000018 property. */
    private java.lang.String c680000018;

    /** The value of the simple c680000019 property. */
    private java.lang.String c680000019;

    /** The value of the simple c680000020 property. */
    private java.lang.String c680000020;

    /** The value of the simple c680000021 property. */
    private java.lang.String c680000021;

    /**
     * Simple constructor of AbstractT223 instances.
     */
    public AbstractT223()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C680000001 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000001()
    {
        return this.c680000001;
    }

    /**
     * Set the value of the C680000001 column.
     * @param c680000001
     */
    public void setC680000001(java.lang.String c680000001)
    {
        this.c680000001 = c680000001;
    }

    /**
     * Return the value of the C680000002 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000002()
    {
        return this.c680000002;
    }

    /**
     * Set the value of the C680000002 column.
     * @param c680000002
     */
    public void setC680000002(java.lang.String c680000002)
    {
        this.c680000002 = c680000002;
    }

    /**
     * Return the value of the C680000003 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000003()
    {
        return this.c680000003;
    }

    /**
     * Set the value of the C680000003 column.
     * @param c680000003
     */
    public void setC680000003(java.lang.String c680000003)
    {
        this.c680000003 = c680000003;
    }

    /**
     * Return the value of the C680000004 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000004()
    {
        return this.c680000004;
    }

    /**
     * Set the value of the C680000004 column.
     * @param c680000004
     */
    public void setC680000004(java.lang.String c680000004)
    {
        this.c680000004 = c680000004;
    }

    /**
     * Return the value of the C680000005 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000005()
    {
        return this.c680000005;
    }

    /**
     * Set the value of the C680000005 column.
     * @param c680000005
     */
    public void setC680000005(java.lang.String c680000005)
    {
        this.c680000005 = c680000005;
    }

    /**
     * Return the value of the C680000006 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000006()
    {
        return this.c680000006;
    }

    /**
     * Set the value of the C680000006 column.
     * @param c680000006
     */
    public void setC680000006(java.lang.String c680000006)
    {
        this.c680000006 = c680000006;
    }

    /**
     * Return the value of the C680000007 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000007()
    {
        return this.c680000007;
    }

    /**
     * Set the value of the C680000007 column.
     * @param c680000007
     */
    public void setC680000007(java.lang.String c680000007)
    {
        this.c680000007 = c680000007;
    }

    /**
     * Return the value of the C680000008 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000008()
    {
        return this.c680000008;
    }

    /**
     * Set the value of the C680000008 column.
     * @param c680000008
     */
    public void setC680000008(java.lang.String c680000008)
    {
        this.c680000008 = c680000008;
    }

    /**
     * Return the value of the C680000009 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000009()
    {
        return this.c680000009;
    }

    /**
     * Set the value of the C680000009 column.
     * @param c680000009
     */
    public void setC680000009(java.lang.String c680000009)
    {
        this.c680000009 = c680000009;
    }

    /**
     * Return the value of the C680000010 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000010()
    {
        return this.c680000010;
    }

    /**
     * Set the value of the C680000010 column.
     * @param c680000010
     */
    public void setC680000010(java.lang.String c680000010)
    {
        this.c680000010 = c680000010;
    }

    /**
     * Return the value of the C680000011 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000011()
    {
        return this.c680000011;
    }

    /**
     * Set the value of the C680000011 column.
     * @param c680000011
     */
    public void setC680000011(java.lang.String c680000011)
    {
        this.c680000011 = c680000011;
    }

    /**
     * Return the value of the C680000012 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000012()
    {
        return this.c680000012;
    }

    /**
     * Set the value of the C680000012 column.
     * @param c680000012
     */
    public void setC680000012(java.lang.String c680000012)
    {
        this.c680000012 = c680000012;
    }

    /**
     * Return the value of the C680000013 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000013()
    {
        return this.c680000013;
    }

    /**
     * Set the value of the C680000013 column.
     * @param c680000013
     */
    public void setC680000013(java.lang.String c680000013)
    {
        this.c680000013 = c680000013;
    }

    /**
     * Return the value of the C680000014 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000014()
    {
        return this.c680000014;
    }

    /**
     * Set the value of the C680000014 column.
     * @param c680000014
     */
    public void setC680000014(java.lang.String c680000014)
    {
        this.c680000014 = c680000014;
    }

    /**
     * Return the value of the C680000015 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000015()
    {
        return this.c680000015;
    }

    /**
     * Set the value of the C680000015 column.
     * @param c680000015
     */
    public void setC680000015(java.lang.String c680000015)
    {
        this.c680000015 = c680000015;
    }

    /**
     * Return the value of the C680000016 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000016()
    {
        return this.c680000016;
    }

    /**
     * Set the value of the C680000016 column.
     * @param c680000016
     */
    public void setC680000016(java.lang.String c680000016)
    {
        this.c680000016 = c680000016;
    }

    /**
     * Return the value of the C680000017 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000017()
    {
        return this.c680000017;
    }

    /**
     * Set the value of the C680000017 column.
     * @param c680000017
     */
    public void setC680000017(java.lang.String c680000017)
    {
        this.c680000017 = c680000017;
    }

    /**
     * Return the value of the C680000018 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000018()
    {
        return this.c680000018;
    }

    /**
     * Set the value of the C680000018 column.
     * @param c680000018
     */
    public void setC680000018(java.lang.String c680000018)
    {
        this.c680000018 = c680000018;
    }

    /**
     * Return the value of the C680000019 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000019()
    {
        return this.c680000019;
    }

    /**
     * Set the value of the C680000019 column.
     * @param c680000019
     */
    public void setC680000019(java.lang.String c680000019)
    {
        this.c680000019 = c680000019;
    }

    /**
     * Return the value of the C680000020 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000020()
    {
        return this.c680000020;
    }

    /**
     * Set the value of the C680000020 column.
     * @param c680000020
     */
    public void setC680000020(java.lang.String c680000020)
    {
        this.c680000020 = c680000020;
    }

    /**
     * Return the value of the C680000021 column.
     * @return java.lang.String
     */
    public java.lang.String getC680000021()
    {
        return this.c680000021;
    }

    /**
     * Set the value of the C680000021 column.
     * @param c680000021
     */
    public void setC680000021(java.lang.String c680000021)
    {
        this.c680000021 = c680000021;
    }
}
