/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Oct 17 17:04:36 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.rolemanage.people.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T94 table. 
 * You can customize the behavior of this class by editing the class, {@link T94()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT94 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c630000001 property. */
    private java.lang.String c630000001;

    /** The value of the simple c630000002 property. */
    private java.lang.String c630000002;

    /** The value of the simple c630000003 property. */
    private java.lang.String c630000003;

    /** The value of the simple c630000004 property. */
    private java.lang.String c630000004;

    /** The value of the simple c630000005 property. */
    private java.lang.String c630000005;

    /** The value of the simple c630000006 property. */
    private java.lang.String c630000006;

    /** The value of the simple c630000007 property. */
    private java.lang.String c630000007;

    /** The value of the simple c630000008 property. */
    private java.lang.String c630000008;

    /** The value of the simple c630000009 property. */
    private java.lang.String c630000009;

    /** The value of the simple c630000010 property. */
    private java.lang.String c630000010;

    /** The value of the simple c630000011 property. */
    private java.lang.String c630000011;

    /** The value of the simple c630000012 property. */
    private java.lang.String c630000012;

    /** The value of the simple c630000013 property. */
    private java.lang.String c630000013;

    /** The value of the simple c630000014 property. */
    private java.lang.String c630000014;

    /** The value of the simple c630000015 property. */
    private java.lang.String c630000015;

    /** The value of the simple c630000016 property. */
    private java.lang.String c630000016;

    /** The value of the simple c630000017 property. */
    private java.lang.String c630000017;
    
    /** The value of the simple c630000029 property. */
    private java.lang.Long c630000029;
    
    /** The value of the simple c630000036 property. */
    private java.lang.String c630000036;
    
    private java.lang.String c639900003;
    
    private java.lang.String c639900004;
    
    private java.lang.String c639900005;


	/**
     * Simple constructor of AbstractT94 instances.
     */
    public AbstractT94()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C630000001 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000001()
    {
        return this.c630000001;
    }

    /**
     * Set the value of the C630000001 column.
     * @param c630000001
     */
    public void setC630000001(java.lang.String c630000001)
    {
        this.c630000001 = c630000001;
    }

    /**
     * Return the value of the C630000002 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000002()
    {
        return this.c630000002;
    }

    /**
     * Set the value of the C630000002 column.
     * @param c630000002
     */
    public void setC630000002(java.lang.String c630000002)
    {
        this.c630000002 = c630000002;
    }

    /**
     * Return the value of the C630000003 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000003()
    {
        return this.c630000003;
    }

    /**
     * Set the value of the C630000003 column.
     * @param c630000003
     */
    public void setC630000003(java.lang.String c630000003)
    {
        this.c630000003 = c630000003;
    }

    /**
     * Return the value of the C630000004 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000004()
    {
        return this.c630000004;
    }

    /**
     * Set the value of the C630000004 column.
     * @param c630000004
     */
    public void setC630000004(java.lang.String c630000004)
    {
        this.c630000004 = c630000004;
    }

    /**
     * Return the value of the C630000005 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000005()
    {
        return this.c630000005;
    }

    /**
     * Set the value of the C630000005 column.
     * @param c630000005
     */
    public void setC630000005(java.lang.String c630000005)
    {
        this.c630000005 = c630000005;
    }

    /**
     * Return the value of the C630000006 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000006()
    {
        return this.c630000006;
    }

    /**
     * Set the value of the C630000006 column.
     * @param c630000006
     */
    public void setC630000006(java.lang.String c630000006)
    {
        this.c630000006 = c630000006;
    }

    /**
     * Return the value of the C630000007 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000007()
    {
        return this.c630000007;
    }

    /**
     * Set the value of the C630000007 column.
     * @param c630000007
     */
    public void setC630000007(java.lang.String c630000007)
    {
        this.c630000007 = c630000007;
    }

    /**
     * Return the value of the C630000008 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000008()
    {
        return this.c630000008;
    }

    /**
     * Set the value of the C630000008 column.
     * @param c630000008
     */
    public void setC630000008(java.lang.String c630000008)
    {
        this.c630000008 = c630000008;
    }

    /**
     * Return the value of the C630000009 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000009()
    {
        return this.c630000009;
    }

    /**
     * Set the value of the C630000009 column.
     * @param c630000009
     */
    public void setC630000009(java.lang.String c630000009)
    {
        this.c630000009 = c630000009;
    }

    /**
     * Return the value of the C630000010 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000010()
    {
        return this.c630000010;
    }

    /**
     * Set the value of the C630000010 column.
     * @param c630000010
     */
    public void setC630000010(java.lang.String c630000010)
    {
        this.c630000010 = c630000010;
    }

    /**
     * Return the value of the C630000011 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000011()
    {
        return this.c630000011;
    }

    /**
     * Set the value of the C630000011 column.
     * @param c630000011
     */
    public void setC630000011(java.lang.String c630000011)
    {
        this.c630000011 = c630000011;
    }

    /**
     * Return the value of the C630000012 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000012()
    {
        return this.c630000012;
    }

    /**
     * Set the value of the C630000012 column.
     * @param c630000012
     */
    public void setC630000012(java.lang.String c630000012)
    {
        this.c630000012 = c630000012;
    }

    /**
     * Return the value of the C630000013 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000013()
    {
        return this.c630000013;
    }

    /**
     * Set the value of the C630000013 column.
     * @param c630000013
     */
    public void setC630000013(java.lang.String c630000013)
    {
        this.c630000013 = c630000013;
    }

    /**
     * Return the value of the C630000014 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000014()
    {
        return this.c630000014;
    }

    /**
     * Set the value of the C630000014 column.
     * @param c630000014
     */
    public void setC630000014(java.lang.String c630000014)
    {
        this.c630000014 = c630000014;
    }

    /**
     * Return the value of the C630000015 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000015()
    {
        return this.c630000015;
    }

    /**
     * Set the value of the C630000015 column.
     * @param c630000015
     */
    public void setC630000015(java.lang.String c630000015)
    {
        this.c630000015 = c630000015;
    }

    /**
     * Return the value of the C630000016 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000016()
    {
        return this.c630000016;
    }

    /**
     * Set the value of the C630000016 column.
     * @param c630000016
     */
    public void setC630000016(java.lang.String c630000016)
    {
        this.c630000016 = c630000016;
    }

    /**
     * Return the value of the C630000017 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000017()
    {
        return this.c630000017;
    }

    /**
     * Set the value of the C630000017 column.
     * @param c630000017
     */
    public void setC630000017(java.lang.String c630000017)
    {
        this.c630000017 = c630000017;
    }
    
    /**
     * Return the value of the C630000029 column.
     * @return java.lang.String
     */
    public java.lang.Long getC630000029()
    {
        return this.c630000029;
    }

    /**
     * Set the value of the C630000029 column.
     * @param c630000029
     */
    public void setC630000029(java.lang.Long c630000029)
    {
        this.c630000029 = c630000029;
    }

    /**
     * Return the value of the C630000036 column.
     * @return java.lang.String
     */
	public java.lang.String getC630000036() {
		return c630000036;
	}

	/**
     * Set the value of the C630000036 column.
     * @param c630000036
     */
	public void setC630000036(java.lang.String c630000036) {
		this.c630000036 = c630000036;
	}

	public java.lang.String getC639900003() {
		return c639900003;
	}

	public void setC639900003(java.lang.String c639900003) {
		this.c639900003 = c639900003;
	}

	public java.lang.String getC639900004() {
		return c639900004;
	}

	public void setC639900004(java.lang.String c639900004) {
		this.c639900004 = c639900004;
	}
	
	public java.lang.String getC639900005() {
		return c639900005;
	}

	public void setC639900005(java.lang.String c639900005) {
		this.c639900005 = c639900005;
	}
}
