/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Oct 16 12:00:42 GMT 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.sla.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T85 table. 
 * You can customize the behavior of this class by editing the class, {@link T85()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT85 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c600000001 property. */
    private java.lang.String c600000001;

    /** The value of the simple c600000002 property. */
    private java.lang.String c600000002;

    /** The value of the simple c600000003 property. */
    private java.lang.String c600000003;

    /** The value of the simple c600000004 property. */
    private java.lang.String c600000004;

    /** The value of the simple c600000005 property. */
    private java.lang.String c600000005;

    /** The value of the simple c600000006 property. */
    private java.lang.String c600000006;

    /** The value of the simple c600000007 property. */
    private java.lang.String c600000007;

    /** The value of the simple c600000008 property. */
    private java.lang.String c600000008;

    /**
     * Simple constructor of AbstractT85 instances.
     */
    public AbstractT85()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C600000001 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000001()
    {
        return this.c600000001;
    }

    /**
     * Set the value of the C600000001 column.
     * @param c600000001
     */
    public void setC600000001(java.lang.String c600000001)
    {
        this.c600000001 = c600000001;
    }

    /**
     * Return the value of the C600000002 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000002()
    {
        return this.c600000002;
    }

    /**
     * Set the value of the C600000002 column.
     * @param c600000002
     */
    public void setC600000002(java.lang.String c600000002)
    {
        this.c600000002 = c600000002;
    }

    /**
     * Return the value of the C600000003 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000003()
    {
        return this.c600000003;
    }

    /**
     * Set the value of the C600000003 column.
     * @param c600000003
     */
    public void setC600000003(java.lang.String c600000003)
    {
        this.c600000003 = c600000003;
    }

    /**
     * Return the value of the C600000004 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000004()
    {
        return this.c600000004;
    }

    /**
     * Set the value of the C600000004 column.
     * @param c600000004
     */
    public void setC600000004(java.lang.String c600000004)
    {
        this.c600000004 = c600000004;
    }

    /**
     * Return the value of the C600000005 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000005()
    {
        return this.c600000005;
    }

    /**
     * Set the value of the C600000005 column.
     * @param c600000005
     */
    public void setC600000005(java.lang.String c600000005)
    {
        this.c600000005 = c600000005;
    }

    /**
     * Return the value of the C600000006 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000006()
    {
        return this.c600000006;
    }

    /**
     * Set the value of the C600000006 column.
     * @param c600000006
     */
    public void setC600000006(java.lang.String c600000006)
    {
        this.c600000006 = c600000006;
    }

    /**
     * Return the value of the C600000007 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000007()
    {
        return this.c600000007;
    }

    /**
     * Set the value of the C600000007 column.
     * @param c600000007
     */
    public void setC600000007(java.lang.String c600000007)
    {
        this.c600000007 = c600000007;
    }

    /**
     * Return the value of the C600000008 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000008()
    {
        return this.c600000008;
    }

    /**
     * Set the value of the C600000008 column.
     * @param c600000008
     */
    public void setC600000008(java.lang.String c600000008)
    {
        this.c600000008 = c600000008;
    }
}
