/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Oct 17 07:00:33 GMT 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.sla.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T110 table. 
 * You can customize the behavior of this class by editing the class, {@link T110()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT110 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c600000021 property. */
    private java.lang.String c600000021;

    /** The value of the simple c600000023 property. */
    private java.lang.String c600000023;

    /** The value of the simple c600000025 property. */
    private java.lang.String c600000025;

    /** The value of the simple c600000024 property. */
    private java.lang.String c600000024;

    /** The value of the simple c600000022 property. */
    private java.lang.String c600000022;

    /** The value of the simple c600000035 property. */
    private java.lang.String c600000035;

    /**
     * Simple constructor of AbstractT110 instances.
     */
    public AbstractT110()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C600000021 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000021()
    {
        return this.c600000021;
    }

    /**
     * Set the value of the C600000021 column.
     * @param c600000021
     */
    public void setC600000021(java.lang.String c600000021)
    {
        this.c600000021 = c600000021;
    }

    /**
     * Return the value of the C600000023 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000023()
    {
        return this.c600000023;
    }

    /**
     * Set the value of the C600000023 column.
     * @param c600000023
     */
    public void setC600000023(java.lang.String c600000023)
    {
        this.c600000023 = c600000023;
    }

    /**
     * Return the value of the C600000025 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000025()
    {
        return this.c600000025;
    }

    /**
     * Set the value of the C600000025 column.
     * @param c600000025
     */
    public void setC600000025(java.lang.String c600000025)
    {
        this.c600000025 = c600000025;
    }

    /**
     * Return the value of the C600000024 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000024()
    {
        return this.c600000024;
    }

    /**
     * Set the value of the C600000024 column.
     * @param c600000024
     */
    public void setC600000024(java.lang.String c600000024)
    {
        this.c600000024 = c600000024;
    }

    /**
     * Return the value of the C600000022 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000022()
    {
        return this.c600000022;
    }

    /**
     * Set the value of the C600000022 column.
     * @param c600000022
     */
    public void setC600000022(java.lang.String c600000022)
    {
        this.c600000022 = c600000022;
    }

    /**
     * Return the value of the C600000035 column.
     * @return java.lang.String
     */
    public java.lang.String getC600000035()
    {
        return this.c600000035;
    }

    /**
     * Set the value of the C600000035 column.
     * @param c600000035
     */
    public void setC600000035(java.lang.String c600000035)
    {
        this.c600000035 = c600000035;
    }
}
