/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Oct 21 16:14:50 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.sendscope.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T97 table. 
 * You can customize the behavior of this class by editing the class, {@link T97()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT97 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c610000020 property. */
    private java.lang.String c610000020;

    /** The value of the simple c610000021 property. */
    private java.lang.String c610000021;

    /** The value of the simple c610000022 property. */
    private java.lang.String c610000022;

    /** The value of the simple c610000023 property. */
    private java.lang.String c610000023;

    /** The value of the simple c610000024 property. */
    private java.lang.String c610000024;
    
    private java.lang.String c610000025;
    
    private java.lang.String c610000026;
    
    private java.lang.String c610000027;
    
    private java.lang.String c610000028;
    
    private java.lang.String c610000029;

    /**
     * Simple constructor of AbstractT97 instances.
     */
    public AbstractT97()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C610000020 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000020()
    {
        return this.c610000020;
    }

    /**
     * Set the value of the C610000020 column.
     * @param c610000020
     */
    public void setC610000020(java.lang.String c610000020)
    {
        this.c610000020 = c610000020;
    }

    /**
     * Return the value of the C610000021 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000021()
    {
        return this.c610000021;
    }

    /**
     * Set the value of the C610000021 column.
     * @param c610000021
     */
    public void setC610000021(java.lang.String c610000021)
    {
        this.c610000021 = c610000021;
    }

    /**
     * Return the value of the C610000022 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000022()
    {
        return this.c610000022;
    }

    /**
     * Set the value of the C610000022 column.
     * @param c610000022
     */
    public void setC610000022(java.lang.String c610000022)
    {
        this.c610000022 = c610000022;
    }

    /**
     * Return the value of the C610000023 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000023()
    {
        return this.c610000023;
    }

    /**
     * Set the value of the C610000023 column.
     * @param c610000023
     */
    public void setC610000023(java.lang.String c610000023)
    {
        this.c610000023 = c610000023;
    }

    /**
     * Return the value of the C610000024 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000024()
    {
        return this.c610000024;
    }

    /**
     * Set the value of the C610000024 column.
     * @param c610000024
     */
    public void setC610000024(java.lang.String c610000024)
    {
        this.c610000024 = c610000024;
    }
    /**
     * Return the value of the C610000025 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000025()
    {
        return this.c610000025;
    }

    /**
     * Set the value of the C610000025 column.
     * @param c610000025
     */
    public void setC610000025(java.lang.String c610000025)
    {
        this.c610000025 = c610000025;
    }
    
    /**
     * Return the value of the C610000026 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000026()
    {
        return this.c610000026;
    }

    /**
     * Set the value of the C610000026 column.
     * @param c610000026
     */
    public void setC610000026(java.lang.String c610000026)
    {
        this.c610000026 = c610000026;
    }
    
    /**
     * Return the value of the C610000027 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000027()
    {
        return this.c610000027;
    }

    /**
     * Set the value of the C610000027 column.
     * @param c610000027
     */
    public void setC610000027(java.lang.String c610000027)
    {
        this.c610000027 = c610000027;
    }
    
    /**
     * Return the value of the C610000028 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000028()
    {
        return this.c610000028;
    }

    /**
     * Set the value of the C610000028 column.
     * @param c610000028
     */
    public void setC610000028(java.lang.String c610000028)
    {
        this.c610000028 = c610000028;
    }
    
    /**
     * Return the value of the C610000029 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000029()
    {
        return this.c610000029;
    }

    /**
     * Set the value of the C610000029 column.
     * @param c610000029
     */
    public void setC610000029(java.lang.String c610000029)
    {
        this.c610000029 = c610000029;
    }
    
    
    
    
    
    
}
