/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jan 16 15:13:39 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.sendscope.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the USERSENDSCOPE table. 
 * You can customize the behavior of this class by editing the class, {@link Usersendscope()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUsersendscope 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple groupname property. */
    private java.lang.String groupnameid;

    /** The value of the simple userid property. */
    private java.lang.String userid;

    /** The value of the simple groupid property. */
    private java.lang.String groupid;

    /** The value of the simple grandid property. */
    private java.lang.String grandid;

    /** The value of the simple notes property. */
    private java.lang.String note;

    /** The value of the simple memo property. */
    private java.lang.String memo;

    /** The value of the simple memo1 property. */
    private java.lang.String memo1;
    
    private java.lang.String sourceid;

    private java.lang.String sendscopetype;
    
    public java.lang.String getSourceid()
	{
		return sourceid;
	}

	public void setSourceid(java.lang.String sourceid)
	{
		this.sourceid = sourceid;
	}

	/**
     * Simple constructor of AbstractUsersendscope instances.
     */
    public AbstractUsersendscope()
    {
    }

    /**
     * Constructor of AbstractUsersendscope instances given a simple primary key.
     * @param id
     */
    public AbstractUsersendscope(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }



    /**
     * Return the value of the USERID column.
     * @return java.lang.String
     */
    public java.lang.String getUserid()
    {
        return this.userid;
    }

    /**
     * Set the value of the USERID column.
     * @param userid
     */
    public void setUserid(java.lang.String userid)
    {
        this.userid = userid;
    }

    /**
     * Return the value of the GROUPID column.
     * @return java.lang.String
     */
    public java.lang.String getGroupid()
    {
        return this.groupid;
    }

    /**
     * Set the value of the GROUPID column.
     * @param groupid
     */
    public void setGroupid(java.lang.String groupid)
    {
        this.groupid = groupid;
    }

    /**
     * Return the value of the GRANDID column.
     * @return java.lang.String
     */
    public java.lang.String getGrandid()
    {
        return this.grandid;
    }

    /**
     * Set the value of the GRANDID column.
     * @param grandid
     */
    public void setGrandid(java.lang.String grandid)
    {
        this.grandid = grandid;
    }

    /**
     * Return the value of the NOTE column.
     * @return java.lang.String
     */
    public java.lang.String getNote()
    {
        return this.note;
    }

    /**
     * Set the value of the NOTE column.
     * @param note
     */
    public void setNote(java.lang.String note)
    {
        this.note = note;
    }

    /**
     * Return the value of the MEMO column.
     * @return java.lang.String
     */
    public java.lang.String getMemo()
    {
        return this.memo;
    }

    /**
     * Set the value of the MEMO column.
     * @param memo
     */
    public void setMemo(java.lang.String memo)
    {
        this.memo = memo;
    }

    /**
     * Return the value of the MEMO1 column.
     * @return java.lang.String
     */
    public java.lang.String getMemo1()
    {
        return this.memo1;
    }

    /**
     * Set the value of the MEMO1 column.
     * @param memo1
     */
    public void setMemo1(java.lang.String memo1)
    {
        this.memo1 = memo1;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof UserSendScope))
            return false;
        UserSendScope that = (UserSendScope) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public java.lang.String getSendscopetype()
	{
		return sendscopetype;
	}

	public void setSendscopetype(java.lang.String sendscopetype)
	{
		this.sendscopetype = sendscopetype;
	}

	public java.lang.String getGroupnameid()
	{
		return groupnameid;
	}

	public void setGroupnameid(java.lang.String groupnameid)
	{
		this.groupnameid = groupnameid;
	}
}
