/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Jan 19 13:27:26 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.sendscope.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the USERSENDSCOPENAMEMAG table. 
 * You can customize the behavior of this class by editing the class, {@link Usersendscopenamemag()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractUsersendscopenamemag 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple groupname property. */
    private java.lang.String groupname;

    /** The value of the simple memo property. */
    private java.lang.String memo;

    /**
     * Simple constructor of AbstractUsersendscopenamemag instances.
     */
    public AbstractUsersendscopenamemag()
    {
    }

    /**
     * Constructor of AbstractUsersendscopenamemag instances given a simple primary key.
     * @param id
     */
    public AbstractUsersendscopenamemag(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the GROUPNAME column.
     * @return java.lang.String
     */
    public java.lang.String getGroupname()
    {
        return this.groupname;
    }

    /**
     * Set the value of the GROUPNAME column.
     * @param groupname
     */
    public void setGroupname(java.lang.String groupname)
    {
        this.groupname = groupname;
    }

    /**
     * Return the value of the MEMO column.
     * @return java.lang.String
     */
    public java.lang.String getMemo()
    {
        return this.memo;
    }

    /**
     * Set the value of the MEMO column.
     * @param memo
     */
    public void setMemo(java.lang.String memo)
    {
        this.memo = memo;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof UserSendScopeNameMag))
            return false;
        UserSendScopeNameMag that = (UserSendScopeNameMag) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
