/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Nov 16 17:39:35 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.common.bean.base;

import java.io.Serializable;

import cn.com.ultrapower.eoms.common.bean.po.PageSet;

/**
 * A class that represents a row in the PAGE_SET table. 
 * You can customize the behavior of this class by editing the class, {@link PageSet()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractPageSet 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long divid;

    /** The value of the simple pageName property. */
    private java.lang.String pageName;

    /** The value of the simple columnName property. */
    private java.lang.String columnName;

    /** The value of the simple divcount property. */
    private java.lang.Long divcount;

    /** The value of the simple divname property. */
    private java.lang.String divname;

    /** The value of the simple divheight property. */
    private java.lang.String divheight;

    /** The value of the simple displayContent property. */
    private java.lang.String displayContent;

    /** The value of the simple parentPageName property. */
    private java.lang.String parentPageName;
    
    /** The value of the simple userId property. */
    private java.lang.Long userId;
    /**
     * Simple constructor of AbstractPageSet instances.
     */
    public AbstractPageSet()
    {
    }

    /**
     * Constructor of AbstractPageSet instances given a simple primary key.
     * @param divid
     */
    public AbstractPageSet(java.lang.Long divid)
    {
        this.setDivid(divid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getDivid()
    {
        return divid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param divid
     */
    public void setDivid(java.lang.Long divid)
    {
        this.hashValue = 0;
        this.divid = divid;
    }

    /**
     * Return the value of the PAGE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getPageName()
    {
        return this.pageName;
    }

    /**
     * Set the value of the PAGE_NAME column.
     * @param pageName
     */
    public void setPageName(java.lang.String pageName)
    {
        this.pageName = pageName;
    }

    /**
     * Return the value of the COLUMN_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getColumnName()
    {
        return this.columnName;
    }

    /**
     * Set the value of the COLUMN_NAME column.
     * @param columnName
     */
    public void setColumnName(java.lang.String columnName)
    {
        this.columnName = columnName;
    }

    /**
     * Return the value of the DIVCOUNT column.
     * @return java.lang.Long
     */
    public java.lang.Long getDivcount()
    {
        return this.divcount;
    }

    /**
     * Set the value of the DIVCOUNT column.
     * @param divcount
     */
    public void setDivcount(java.lang.Long divcount)
    {
        this.divcount = divcount;
    }

    /**
     * Return the value of the DIVNAME column.
     * @return java.lang.String
     */
    public java.lang.String getDivname()
    {
        return this.divname;
    }

    /**
     * Set the value of the DIVNAME column.
     * @param divname
     */
    public void setDivname(java.lang.String divname)
    {
        this.divname = divname;
    }

    /**
     * Return the value of the DIVHEIGHT column.
     * @return java.lang.String
     */
    public java.lang.String getDivheight()
    {
        return this.divheight;
    }

    /**
     * Set the value of the DIVHEIGHT column.
     * @param divheight
     */
    public void setDivheight(java.lang.String divheight)
    {
        this.divheight = divheight;
    }

    /**
     * Return the value of the DISPLAY_CONTENT column.
     * @return java.lang.String
     */
    public java.lang.String getDisplayContent()
    {
        return this.displayContent;
    }

    /**
     * Set the value of the DISPLAY_CONTENT column.
     * @param displayContent
     */
    public void setDisplayContent(java.lang.String displayContent)
    {
        this.displayContent = displayContent;
    }

    /**
     * Return the value of the PARENT_PAGE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getParentPageName()
    {
        return this.parentPageName;
    }

    /**
     * Set the value of the PARENT_PAGE_NAME column.
     * @param parentPageName
     */
    public void setParentPageName(java.lang.String parentPageName)
    {
        this.parentPageName = parentPageName;
    }

    public java.lang.Long getUserId()
    {
        return this.userId;
    }

    /**
     * Set the value of the FILL_USER_ID column.
     * @param UserId
     */
    public void setUserId(java.lang.Long userId)
    {
        this.userId = userId;
    }
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof PageSet))
            return false;
        PageSet that = (PageSet) rhs;
        if (this.getDivid() == null || that.getDivid() == null)
            return false;
        return (this.getDivid().equals(that.getDivid()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int dividValue = this.getDivid() == null ? 0 : this.getDivid().hashCode();
            result = result * 37 + dividValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
