/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Oct 18 15:21:09 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.rolemanage.group.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T106 table. 
 * You can customize the behavior of this class by editing the class, {@link T106()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT106 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c630000018 property. */
    private java.lang.String c630000018;

    /** The value of the simple c630000019 property. */
    private java.lang.String c630000019;

    /** The value of the simple c630000020 property. */
    private java.lang.String c630000020;

    /** The value of the simple c630000021 property. */
    private java.lang.String c630000021;

    /** The value of the simple c630000022 property. */
    private java.lang.String c630000022;

    /** The value of the simple c630000023 property. */
    private java.lang.String c630000023;

    /** The value of the simple c630000024 property. */
    private java.lang.String c630000024;

    /** The value of the simple c630000025 property. */
    private java.lang.String c630000025;

    /** The value of the simple c630000026 property. */
    private java.lang.String c630000026;

    /** The value of the simple c630000027 property. */
    private java.lang.String c630000027;

    /** The value of the simple c630000028 property. */
    private java.lang.String c630000028;
    
    /** The value of the simple c630000030 property. */
    private java.lang.Long c630000030;
    
    /** The value of the simple c630000037 property. */
    private java.lang.String c630000037;

    /**
     * Simple constructor of AbstractT106 instances.
     */
    public AbstractT106()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C630000018 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000018()
    {
        return this.c630000018;
    }

    /**
     * Set the value of the C630000018 column.
     * @param c630000018
     */
    public void setC630000018(java.lang.String c630000018)
    {
        this.c630000018 = c630000018;
    }

    /**
     * Return the value of the C630000019 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000019()
    {
        return this.c630000019;
    }

    /**
     * Set the value of the C630000019 column.
     * @param c630000019
     */
    public void setC630000019(java.lang.String c630000019)
    {
        this.c630000019 = c630000019;
    }

    /**
     * Return the value of the C630000020 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000020()
    {
        return this.c630000020;
    }

    /**
     * Set the value of the C630000020 column.
     * @param c630000020
     */
    public void setC630000020(java.lang.String c630000020)
    {
        this.c630000020 = c630000020;
    }

    /**
     * Return the value of the C630000021 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000021()
    {
        return this.c630000021;
    }

    /**
     * Set the value of the C630000021 column.
     * @param c630000021
     */
    public void setC630000021(java.lang.String c630000021)
    {
        this.c630000021 = c630000021;
    }

    /**
     * Return the value of the C630000022 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000022()
    {
        return this.c630000022;
    }

    /**
     * Set the value of the C630000022 column.
     * @param c630000022
     */
    public void setC630000022(java.lang.String c630000022)
    {
        this.c630000022 = c630000022;
    }

    /**
     * Return the value of the C630000023 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000023()
    {
        return this.c630000023;
    }

    /**
     * Set the value of the C630000023 column.
     * @param c630000023
     */
    public void setC630000023(java.lang.String c630000023)
    {
        this.c630000023 = c630000023;
    }

    /**
     * Return the value of the C630000024 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000024()
    {
        return this.c630000024;
    }

    /**
     * Set the value of the C630000024 column.
     * @param c630000024
     */
    public void setC630000024(java.lang.String c630000024)
    {
        this.c630000024 = c630000024;
    }

    /**
     * Return the value of the C630000025 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000025()
    {
        return this.c630000025;
    }

    /**
     * Set the value of the C630000025 column.
     * @param c630000025
     */
    public void setC630000025(java.lang.String c630000025)
    {
        this.c630000025 = c630000025;
    }

    /**
     * Return the value of the C630000026 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000026()
    {
        return this.c630000026;
    }

    /**
     * Set the value of the C630000026 column.
     * @param c630000026
     */
    public void setC630000026(java.lang.String c630000026)
    {
        this.c630000026 = c630000026;
    }

    /**
     * Return the value of the C630000027 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000027()
    {
        return this.c630000027;
    }

    /**
     * Set the value of the C630000027 column.
     * @param c630000027
     */
    public void setC630000027(java.lang.String c630000027)
    {
        this.c630000027 = c630000027;
    }

    /**
     * Return the value of the C630000028 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000028()
    {
        return this.c630000028;
    }

    /**
     * Set the value of the C630000028 column.
     * @param c630000028
     */
    public void setC630000028(java.lang.String c630000028)
    {
        this.c630000028 = c630000028;
    }
    
    /**
     * Return the value of the C630000030 column.
     * @return java.lang.String
     */
    public java.lang.Long getC630000030()
    {
        return this.c630000030;
    }

    /**
     * Set the value of the C630000028 column.
     * @param c630000030
     */
    public void setC630000030(java.lang.Long c630000030)
    {
        this.c630000030 = c630000030;
    }
    
    /**
     * Return the value of the C630000037 column.
     * @return java.lang.String
     */
    public java.lang.String getC630000037()
    {
        return this.c630000037;
    }

    /**
     * Set the value of the C630000037 column.
     * @param c630000037
     */
    public void setC630000037(java.lang.String c630000037)
    {
        this.c630000037 = c630000037;
    }
    
}
