/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 06 16:22:45 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.rolemanage.group.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T19 table. 
 * You can customize the behavior of this class by editing the class, {@link T19()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT19 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c9 property. */
    private java.lang.String c9;

    /** The value of the simple c105 property. */
    private java.lang.String c105;

    /** The value of the simple c106 property. */
    private java.lang.Long c106;

    /** The value of the simple c107 property. */
    private java.lang.Long c107;

    /** The value of the simple c115 property. */
    private java.lang.Long c115;

    /** The value of the simple c116 property. */
    private java.lang.Long c116;

    /** The value of the simple c120 property. */
    private java.lang.Long c120;

    /** The value of the simple c121 property. */
    private java.lang.String c121;

    /** The value of the simple c179 property. */
    private java.lang.String c179;

    /** The value of the simple c490000000 property. */
    private java.lang.String c490000000;

    /** The value of the simple c490000100 property. */
    private java.lang.String c490000100;

    /**
     * Simple constructor of AbstractT19 instances.
     */
    public AbstractT19()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C9 column.
     * @return java.lang.String
     */
    public java.lang.String getC9()
    {
        return this.c9;
    }

    /**
     * Set the value of the C9 column.
     * @param c9
     */
    public void setC9(java.lang.String c9)
    {
        this.c9 = c9;
    }

    /**
     * Return the value of the C105 column.
     * @return java.lang.String
     */
    public java.lang.String getC105()
    {
        return this.c105;
    }

    /**
     * Set the value of the C105 column.
     * @param c105
     */
    public void setC105(java.lang.String c105)
    {
        this.c105 = c105;
    }

    /**
     * Return the value of the C106 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC106()
    {
        return this.c106;
    }

    /**
     * Set the value of the C106 column.
     * @param c106
     */
    public void setC106(java.lang.Long c106)
    {
        this.c106 = c106;
    }

    /**
     * Return the value of the C107 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC107()
    {
        return this.c107;
    }

    /**
     * Set the value of the C107 column.
     * @param c107
     */
    public void setC107(java.lang.Long c107)
    {
        this.c107 = c107;
    }

    /**
     * Return the value of the C115 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC115()
    {
        return this.c115;
    }

    /**
     * Set the value of the C115 column.
     * @param c115
     */
    public void setC115(java.lang.Long c115)
    {
        this.c115 = c115;
    }

    /**
     * Return the value of the C116 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC116()
    {
        return this.c116;
    }

    /**
     * Set the value of the C116 column.
     * @param c116
     */
    public void setC116(java.lang.Long c116)
    {
        this.c116 = c116;
    }

    /**
     * Return the value of the C120 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC120()
    {
        return this.c120;
    }

    /**
     * Set the value of the C120 column.
     * @param c120
     */
    public void setC120(java.lang.Long c120)
    {
        this.c120 = c120;
    }

    /**
     * Return the value of the C121 column.
     * @return java.lang.String
     */
    public java.lang.String getC121()
    {
        return this.c121;
    }

    /**
     * Set the value of the C121 column.
     * @param c121
     */
    public void setC121(java.lang.String c121)
    {
        this.c121 = c121;
    }

    /**
     * Return the value of the C179 column.
     * @return java.lang.String
     */
    public java.lang.String getC179()
    {
        return this.c179;
    }

    /**
     * Set the value of the C179 column.
     * @param c179
     */
    public void setC179(java.lang.String c179)
    {
        this.c179 = c179;
    }

    /**
     * Return the value of the C490000000 column.
     * @return java.lang.String
     */
    public java.lang.String getC490000000()
    {
        return this.c490000000;
    }

    /**
     * Set the value of the C490000000 column.
     * @param c490000000
     */
    public void setC490000000(java.lang.String c490000000)
    {
        this.c490000000 = c490000000;
    }

    /**
     * Return the value of the C490000100 column.
     * @return java.lang.String
     */
    public java.lang.String getC490000100()
    {
        return this.c490000100;
    }

    /**
     * Set the value of the C490000100 column.
     * @param c490000100
     */
    public void setC490000100(java.lang.String c490000100)
    {
        this.c490000100 = c490000100;
    }
}
