package cn.com.ultrapower.eoms.user.rolemanage.group.hibernate.po;



/**
 * AbstractCompanyrel generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractCompanyrel  implements java.io.Serializable {


    // Fields    

     private Long companyrelId;
     private String companyrelCompanyid;
     private String companyrelDepid;


    // Constructors

    /** default constructor */
    public AbstractCompanyrel() {
    }
   
    // Property accessors

    public Long getCompanyrelId() {
        return this.companyrelId;
    }
    
    public void setCompanyrelId(Long companyrelId) {
        this.companyrelId = companyrelId;
    }

    public String getCompanyrelCompanyid() {
        return this.companyrelCompanyid;
    }
    
    public void setCompanyrelCompanyid(String companyrelCompanyid) {
        this.companyrelCompanyid = companyrelCompanyid;
    }

    public String getCompanyrelDepid() {
        return this.companyrelDepid;
    }
    
    public void setCompanyrelDepid(String companyrelDepid) {
        this.companyrelDepid = companyrelDepid;
    }
   








}