package cn.com.ultrapower.eoms.user.rolemanage.group.hibernate.po;
// Generated by MyEclipse - Hibernate Tools



/**
 * Companyrel generated by MyEclipse - Hibernate Tools
 */
public class Subcompanyrel extends AbstractCompanyrel implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Subcompanyrel() {
    }
}
