/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Oct 21 09:23:55 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.menu.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T74 table. 
 * You can customize the behavior of this class by editing the class, {@link T74()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT74 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c620000015 property. */
    private java.lang.String c620000015;

    /** The value of the simple c620000016 property. */
    private java.lang.String c620000016;

    /** The value of the simple c620000017 property. */
    private java.lang.String c620000017;

    /** The value of the simple c620000018 property. */
    private java.lang.String c620000018;

    /** The value of the simple c620000018 property. */
    private java.lang.String c620000019;
    /**
     * Simple constructor of AbstractT74 instances.
     */
    public AbstractT74()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C620000015 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000015()
    {
        return this.c620000015;
    }

    /**
     * Set the value of the C620000015 column.
     * @param c620000015
     */
    public void setC620000015(java.lang.String c620000015)
    {
        this.c620000015 = c620000015;
    }

    /**
     * Return the value of the C620000016 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000016()
    {
        return this.c620000016;
    }

    /**
     * Set the value of the C620000016 column.
     * @param c620000016
     */
    public void setC620000016(java.lang.String c620000016)
    {
        this.c620000016 = c620000016;
    }

    /**
     * Return the value of the C620000017 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000017()
    {
        return this.c620000017;
    }

    /**
     * Set the value of the C620000017 column.
     * @param c620000017
     */
    public void setC620000017(java.lang.String c620000017)
    {
        this.c620000017 = c620000017;
    }

    /**
     * Return the value of the C620000018 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000018()
    {
        return this.c620000018;
    }

    /**
     * Set the value of the C620000018 column.
     * @param c620000018
     */
    public void setC620000018(java.lang.String c620000018)
    {
        this.c620000018 = c620000018;
    }
    
    /**
     * Return the value of the C620000018 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000019()
    {
        return this.c620000019;
    }

    /**
     * Set the value of the C620000018 column.
     * @param c620000018
     */
    public void setC620000019(java.lang.String c620000019)
    {
        this.c620000019 = c620000019;
    }
}
