/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Oct 31 11:24:23 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.menu.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T139 table. 
 * You can customize the behavior of this class by editing the class, {@link T139()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT139 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c620000032 property. */
    private java.lang.String c620000032;

    /** The value of the simple c620000033 property. */
    private java.lang.String c620000033;

    /** The value of the simple c620000034 property. */
    private java.lang.String c620000034;

    /** The value of the simple c620000035 property. */
    private java.lang.String c620000035;

    /**
     * Simple constructor of AbstractT139 instances.
     */
    public AbstractT139()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C620000032 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000032()
    {
        return this.c620000032;
    }

    /**
     * Set the value of the C620000032 column.
     * @param c620000032
     */
    public void setC620000032(java.lang.String c620000032)
    {
        this.c620000032 = c620000032;
    }

    /**
     * Return the value of the C620000033 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000033()
    {
        return this.c620000033;
    }

    /**
     * Set the value of the C620000033 column.
     * @param c620000033
     */
    public void setC620000033(java.lang.String c620000033)
    {
        this.c620000033 = c620000033;
    }

    /**
     * Return the value of the C620000034 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000034()
    {
        return this.c620000034;
    }

    /**
     * Set the value of the C620000034 column.
     * @param c620000034
     */
    public void setC620000034(java.lang.String c620000034)
    {
        this.c620000034 = c620000034;
    }

    /**
     * Return the value of the C620000035 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000035()
    {
        return this.c620000035;
    }

    /**
     * Set the value of the C620000035 column.
     * @param c620000035
     */
    public void setC620000035(java.lang.String c620000035)
    {
        this.c620000035 = c620000035;
    }
}
