/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Oct 16 19:46:43 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.entryid.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T65 table. 
 * You can customize the behavior of this class by editing the class, {@link T65()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT65 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c620000002 property. */
    private java.lang.String c620000002;

    /** The value of the simple c620000003 property. */
    private java.lang.String c620000003;

    /** The value of the simple c620000004 property. */
    private java.lang.String c620000004;

    /** The value of the simple c620000005 property. */
    private java.lang.String c620000005;

    /**
     * Simple constructor of AbstractT65 instances.
     */
    public AbstractT65()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C620000002 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000002()
    {
        return this.c620000002;
    }

    /**
     * Set the value of the C620000002 column.
     * @param c620000002
     */
    public void setC620000002(java.lang.String c620000002)
    {
        this.c620000002 = c620000002;
    }

    /**
     * Return the value of the C620000003 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000003()
    {
        return this.c620000003;
    }

    /**
     * Set the value of the C620000003 column.
     * @param c620000003
     */
    public void setC620000003(java.lang.String c620000003)
    {
        this.c620000003 = c620000003;
    }

    /**
     * Return the value of the C620000004 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000004()
    {
        return this.c620000004;
    }

    /**
     * Set the value of the C620000004 column.
     * @param c620000004
     */
    public void setC620000004(java.lang.String c620000004)
    {
        this.c620000004 = c620000004;
    }

    /**
     * Return the value of the C620000005 column.
     * @return java.lang.String
     */
    public java.lang.String getC620000005()
    {
        return this.c620000005;
    }

    /**
     * Set the value of the C620000005 column.
     * @param c620000005
     */
    public void setC620000005(java.lang.String c620000005)
    {
        this.c620000005 = c620000005;
    }
}
