package com.ultrapower.eoms.system.usermanager.model;
// default package



/**
 * AbstractUserManagerUserInfor generated by MyEclipse Persistence Tools
 */

public abstract class AbstractUserManagerUserInfor  implements java.io.Serializable {


    // Fields    

     private Long id;
     private String usertype;
     private String code;
     private String department;
     private String sysuserid;
     private String name;
     private String sex;
     private String national;
     private String nativeplace;
     private String birthday;
     private String graduatetime;
     private String college;
     private String education;
     private String degree;
     private String worktime;
     private String zhichen;
     private String zhiwei;
     private String zhiji;
     private String mobile;
     private String telephone;
     private String mail;
     private String speciality1;
     private String speciality2;
     private String isPartymember;
     private String isLeaguemember;
     private String trainerlevel;
     private String expertlevel;
     private String provinceExpertlevel;
     private String remark;
     private String otherphone;
     private String partymemberjointime;
     private String homeaddress;
     private String startworktime;
     private String politicalstatus;
     //20120522新增登陆名字段
     private String loginname;
      //20120808新增字段
     private String graduates;
     private String graduattime;
     private String xwgraduates;
     private String xwgraduattime;
     private String titlesname;
     private String status;
     private String deletetime;
     private String deletereason;
     private String deleteremark;
     
     // 20120906新增职称名称
     private String titlesName;
     //20120925新增身份证号
     private String idcard;
    // Constructors

    public String getGraduates() {
		return graduates;
	}


	public void setGraduates(String graduates) {
		this.graduates = graduates;
	}


	public String getGraduattime() {
		return graduattime;
	}


	public void setGraduattime(String graduattime) {
		this.graduattime = graduattime;
	}


	public String getXwgraduates() {
		return xwgraduates;
	}


	public void setXwgraduates(String xwgraduates) {
		this.xwgraduates = xwgraduates;
	}


	public String getXwgraduattime() {
		return xwgraduattime;
	}


	public void setXwgraduattime(String xwgraduattime) {
		this.xwgraduattime = xwgraduattime;
	}


	public String getTitlesname() {
		return titlesname;
	}


	public void setTitlesname(String titlesname) {
		this.titlesname = titlesname;
	}


	public String getStatus() {
		return status;
	}


	public void setStatus(String status) {
		this.status = status;
	}


	public String getDeletetime() {
		return deletetime;
	}


	public void setDeletetime(String deletetime) {
		this.deletetime = deletetime;
	}


	public String getDeletereason() {
		return deletereason;
	}


	public void setDeletereason(String deletereason) {
		this.deletereason = deletereason;
	}


	public String getDeleteremark() {
		return deleteremark;
	}


	public void setDeleteremark(String deleteremark) {
		this.deleteremark = deleteremark;
	}


	/** default constructor */
    public AbstractUserManagerUserInfor() {
    }
    
    
    /** full constructor */
    public AbstractUserManagerUserInfor(String usertype, String code, String department, String sysuserid, String name, String sex, String national, String nativeplace, String birthday, String graduatetime, String college, String education, String degree, String worktime, String zhichen, String zhiwei, String zhiji, String mobile, String telephone, String mail, String speciality1, String speciality2, String isPartymember, String isLeaguemember, String trainerlevel, String expertlevel, String provinceExpertlevel, String remark,String otherphone,String partymemberjointime,String homeaddress,String startworktime,String politicalstatus,String loginname) {
        this.usertype = usertype;
        this.code = code;
        this.department = department;
        this.sysuserid = sysuserid;
        this.name = name;
        this.sex = sex;
        this.national = national;
        this.nativeplace = nativeplace;
        this.birthday = birthday;
        this.graduatetime = graduatetime;
        this.college = college;
        this.education = education;
        this.degree = degree;
        this.worktime = worktime;
        this.zhichen = zhichen;
        this.zhiwei = zhiwei;
        this.zhiji = zhiji;
        this.mobile = mobile;
        this.telephone = telephone;
        this.mail = mail;
        this.speciality1 = speciality1;
        this.speciality2 = speciality2;
        this.isPartymember = isPartymember;
        this.isLeaguemember = isLeaguemember;
        this.trainerlevel = trainerlevel;
        this.expertlevel = expertlevel;
        this.provinceExpertlevel = provinceExpertlevel;
        this.remark = remark;
        this.otherphone = otherphone;
        this.partymemberjointime = partymemberjointime;
        this.homeaddress = homeaddress;
        this.startworktime = startworktime;
        this.politicalstatus = politicalstatus;
        this.loginname=loginname;
    }

   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getUsertype() {
        return this.usertype;
    }
    
    public void setUsertype(String usertype) {
        this.usertype = usertype;
    }

    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }

    public String getDepartment() {
        return this.department;
    }
    
    public void setDepartment(String department) {
        this.department = department;
    }

    public String getSysuserid() {
        return this.sysuserid;
    }
    
    public void setSysuserid(String sysuserid) {
        this.sysuserid = sysuserid;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getNational() {
        return this.national;
    }
    
    public void setNational(String national) {
        this.national = national;
    }

    public String getNativeplace() {
        return this.nativeplace;
    }
    
    public void setNativeplace(String nativeplace) {
        this.nativeplace = nativeplace;
    }

    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getGraduatetime() {
        return this.graduatetime;
    }
    
    public void setGraduatetime(String graduatetime) {
        this.graduatetime = graduatetime;
    }

    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }

    public String getEducation() {
        return this.education;
    }
    
    public void setEducation(String education) {
        this.education = education;
    }

    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getWorktime() {
        return this.worktime;
    }
    
    public void setWorktime(String worktime) {
        this.worktime = worktime;
    }

    public String getZhichen() {
        return this.zhichen;
    }
    
    public void setZhichen(String zhichen) {
        this.zhichen = zhichen;
    }

    public String getZhiwei() {
        return this.zhiwei;
    }
    
    public void setZhiwei(String zhiwei) {
        this.zhiwei = zhiwei;
    }

    public String getZhiji() {
        return this.zhiji;
    }
    
    public void setZhiji(String zhiji) {
        this.zhiji = zhiji;
    }

    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getSpeciality1() {
        return this.speciality1;
    }
    
    public void setSpeciality1(String speciality1) {
        this.speciality1 = speciality1;
    }

    public String getSpeciality2() {
        return this.speciality2;
    }
    
    public void setSpeciality2(String speciality2) {
        this.speciality2 = speciality2;
    }

    public String getIsPartymember() {
        return this.isPartymember;
    }
    
    public void setIsPartymember(String isPartymember) {
        this.isPartymember = isPartymember;
    }

    public String getIsLeaguemember() {
        return this.isLeaguemember;
    }
    
    public void setIsLeaguemember(String isLeaguemember) {
        this.isLeaguemember = isLeaguemember;
    }

    public String getTrainerlevel() {
        return this.trainerlevel;
    }
    
    public void setTrainerlevel(String trainerlevel) {
        this.trainerlevel = trainerlevel;
    }

    public String getExpertlevel() {
        return this.expertlevel;
    }
    
    public void setExpertlevel(String expertlevel) {
        this.expertlevel = expertlevel;
    }

    public String getProvinceExpertlevel() {
        return this.provinceExpertlevel;
    }
    
    public void setProvinceExpertlevel(String provinceExpertlevel) {
        this.provinceExpertlevel = provinceExpertlevel;
    }

    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }


	public String getOtherphone() {
		return otherphone;
	}


	public void setOtherphone(String otherphone) {
		this.otherphone = otherphone;
	}


	public String getPartymemberjointime() {
		return partymemberjointime;
	}


	public void setPartymemberjointime(String partymemberjointime) {
		this.partymemberjointime = partymemberjointime;
	}


	public String getHomeaddress() {
		return homeaddress;
	}


	public void setHomeaddress(String homeaddress) {
		this.homeaddress = homeaddress;
	}


	public String getStartworktime() {
		return startworktime;
	}


	public void setStartworktime(String startworktime) {
		this.startworktime = startworktime;
	}


	public String getPoliticalstatus() {
		return politicalstatus;
	}


	public void setPoliticalstatus(String politicalstatus) {
		this.politicalstatus = politicalstatus;
	}


	public String getLoginname() {
		return loginname;
	}


	public void setLoginname(String loginname) {
		this.loginname = loginname;
	}

	public String getTitlesName() {
		return titlesName;
	}

	public void setTitlesName(String titlesName) {
		this.titlesName = titlesName;
	}


	public String getIdcard() {
		return idcard;
	}


	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}
}