/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Oct 27 15:02:43 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.source.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the SOURCECONFIGATTRIBUTE table. 
 * You can customize the behavior of this class by editing the class, {@link Sourceconfigattribute()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSourceconfigattribute 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long sourceattId;

    /** The value of the simple sourceattSourceid property. */
    private java.lang.Long sourceattSourceid;

    /** The value of the simple sourceattCnname property. */
    private java.lang.String sourceattCnname;

    /** The value of the simple sourceattEnname property. */
    private java.lang.String sourceattEnname;

    /** The value of the simple sourceattOrderby property. */
    private java.lang.Long sourceattOrderby;

    /** The value of the simple sourceattDesc property. */
    private java.lang.String sourceattDesc;

    private java.lang.String sourceattType;
    
    /**
     * Simple constructor of AbstractSourceconfigattribute instances.
     */
    public AbstractSourceconfigattribute()
    {
    }

    /**
     * Constructor of AbstractSourceconfigattribute instances given a simple primary key.
     * @param sourceattId
     */
    public AbstractSourceconfigattribute(java.lang.Long sourceattId)
    {
        this.setSourceattId(sourceattId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceattId()
    {
        return sourceattId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param sourceattId
     */
    public void setSourceattId(java.lang.Long sourceattId)
    {
        this.hashValue = 0;
        this.sourceattId = sourceattId;
    }

    /**
     * Return the value of the SOURCEATT_SOURCEID column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceattSourceid()
    {
        return this.sourceattSourceid;
    }

    /**
     * Set the value of the SOURCEATT_SOURCEID column.
     * @param sourceattSourceid
     */
    public void setSourceattSourceid(java.lang.Long sourceattSourceid)
    {
        this.sourceattSourceid = sourceattSourceid;
    }

    /**
     * Return the value of the SOURCEATT_CNNAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattCnname()
    {
        return this.sourceattCnname;
    }

    /**
     * Set the value of the SOURCEATT_CNNAME column.
     * @param sourceattCnname
     */
    public void setSourceattCnname(java.lang.String sourceattCnname)
    {
        this.sourceattCnname = sourceattCnname;
    }

    /**
     * Return the value of the SOURCEATT_ENNAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattEnname()
    {
        return this.sourceattEnname;
    }

    /**
     * Set the value of the SOURCEATT_ENNAME column.
     * @param sourceattEnname
     */
    public void setSourceattEnname(java.lang.String sourceattEnname)
    {
        this.sourceattEnname = sourceattEnname;
    }

    /**
     * Return the value of the SOURCEATT_ORDERBY column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceattOrderby()
    {
        return this.sourceattOrderby;
    }

    /**
     * Set the value of the SOURCEATT_ORDERBY column.
     * @param sourceattOrderby
     */
    public void setSourceattOrderby(java.lang.Long sourceattOrderby)
    {
        this.sourceattOrderby = sourceattOrderby;
    }

    /**
     * Return the value of the SOURCEATT_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattDesc()
    {
        return this.sourceattDesc;
    }

    /**
     * Set the value of the SOURCEATT_DESC column.
     * @param sourceattDesc
     */
    public void setSourceattDesc(java.lang.String sourceattDesc)
    {
        this.sourceattDesc = sourceattDesc;
    }
    
    public java.lang.String getSourceattType()
    {
        return this.sourceattType;
    }

    /**
     * Set the value of the SOURCEATT_DESC column.
     * @param sourceattDesc
     */
    public void setSourceattType(java.lang.String sourceattType)
    {
        this.sourceattType = sourceattType;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Sourceconfigattribute))
            return false;
        Sourceconfigattribute that = (Sourceconfigattribute) rhs;
        if (this.getSourceattId() == null || that.getSourceattId() == null)
            return false;
        return (this.getSourceattId().equals(that.getSourceattId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int sourceattIdValue = this.getSourceattId() == null ? 0 : this.getSourceattId().hashCode();
            result = result * 37 + sourceattIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
