/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Oct 31 15:41:17 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.source.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the SOURCECONFIG table. 
 * You can customize the behavior of this class by editing the class, {@link Sourceconfig()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSourceconfig 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long sourceId;

    /** The value of the simple sourceParentid property. */
    private java.lang.Long sourceParentid;

    /** The value of the simple sourceCnname property. */
    private java.lang.String sourceCnname;

    /** The value of the simple sourceName property. */
    private java.lang.String sourceName;

    /** The value of the simple sourceModule property. */
    private java.lang.String sourceModule;

    /** The value of the simple sourceOrderby property. */
    private java.lang.Long sourceOrderby;

    /** The value of the simple sourceDesc property. */
    private java.lang.String sourceDesc;

    /** The value of the simple sourceType property. */
    private java.lang.String sourceType;
    
    private java.lang.String sourceFieldtype;
    
    private java.lang.String sourceUrl;
    
    private java.lang.Long sourceIsleft;
    
    public java.lang.Long getSourceIsleft() {
		return sourceIsleft;
	}

	public void setSourceIsleft(java.lang.Long sourceIsleft) {
		this.sourceIsleft = sourceIsleft;
	}

	public java.lang.String getSourceUrl() {
		return sourceUrl;
	}

	public void setSourceUrl(java.lang.String sourceUrl) {
		this.sourceUrl = sourceUrl;
	}
    /**
     * Simple constructor of AbstractSourceconfig instances.
     */
    public AbstractSourceconfig()
    {
    }

    /**
     * Constructor of AbstractSourceconfig instances given a simple primary key.
     * @param sourceId
     */
    public AbstractSourceconfig(java.lang.Long sourceId)
    {
        this.setSourceId(sourceId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceId()
    {
        return sourceId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param sourceId
     */
    public void setSourceId(java.lang.Long sourceId)
    {
        this.hashValue = 0;
        this.sourceId = sourceId;
    }

    /**
     * Return the value of the SOURCE_PARENTID column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceParentid()
    {
        return this.sourceParentid;
    }

    /**
     * Set the value of the SOURCE_PARENTID column.
     * @param sourceParentid
     */
    public void setSourceParentid(java.lang.Long sourceParentid)
    {
        this.sourceParentid = sourceParentid;
    }

    /**
     * Return the value of the SOURCE_CNNAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceCnname()
    {
        return this.sourceCnname;
    }

    /**
     * Set the value of the SOURCE_CNNAME column.
     * @param sourceCnname
     */
    public void setSourceCnname(java.lang.String sourceCnname)
    {
        this.sourceCnname = sourceCnname;
    }

    /**
     * Return the value of the SOURCE_NAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceName()
    {
        return this.sourceName;
    }

    /**
     * Set the value of the SOURCE_NAME column.
     * @param sourceName
     */
    public void setSourceName(java.lang.String sourceName)
    {
        this.sourceName = sourceName;
    }

    /**
     * Return the value of the SOURCE_MODULE column.
     * @return java.lang.String
     */
    public java.lang.String getSourceModule()
    {
        return this.sourceModule;
    }

    /**
     * Set the value of the SOURCE_MODULE column.
     * @param sourceModule
     */
    public void setSourceModule(java.lang.String sourceModule)
    {
        this.sourceModule = sourceModule;
    }

    /**
     * Return the value of the SOURCE_ORDERBY column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceOrderby()
    {
        return this.sourceOrderby;
    }

    /**
     * Set the value of the SOURCE_ORDERBY column.
     * @param sourceOrderby
     */
    public void setSourceOrderby(java.lang.Long sourceOrderby)
    {
        this.sourceOrderby = sourceOrderby;
    }

    /**
     * Return the value of the SOURCE_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getSourceDesc()
    {
        return this.sourceDesc;
    }

    /**
     * Set the value of the SOURCE_DESC column.
     * @param sourceDesc
     */
    public void setSourceDesc(java.lang.String sourceDesc)
    {
        this.sourceDesc = sourceDesc;
    }

    /**
     * Return the value of the SOURCE_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getSourceType()
    {
        return this.sourceType;
    }

    /**
     * Set the value of the SOURCE_TYPE column.
     * @param sourceType
     */
    public void setSourceType(java.lang.String sourceType)
    {
        this.sourceType = sourceType;
    }
    
    public java.lang.String getSourceFieldtype()
    {
        return this.sourceFieldtype;
    }

    /**
     * Set the value of the SOURCE_TYPE column.
     * @param sourceType
     */
    public void setSourceFieldtype(java.lang.String sourceFieldtype)
    {
        this.sourceFieldtype = sourceFieldtype;
    }
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Sourceconfig))
            return false;
        Sourceconfig that = (Sourceconfig) rhs;
        if (this.getSourceId() == null || that.getSourceId() == null)
            return false;
        return (this.getSourceId().equals(that.getSourceId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int sourceIdValue = this.getSourceId() == null ? 0 : this.getSourceId().hashCode();
            result = result * 37 + sourceIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
