/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Jan 23 14:56:14 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.source.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the SOURCEACTIONCONFIG table. 
 * You can customize the behavior of this class by editing the class, {@link Sourceactionconfig()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSourceactionconfig 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple sourceactionTypeflag property. */
    private java.lang.String sourceactionTypeflag;

    /** The value of the simple sourceactionFieldvalue property. */
    private java.lang.String sourceactionFieldvalue;

    /** The value of the simple sourceactionNumvalue property. */
    private java.lang.String sourceactionNumvalue;

    /** The value of the simple sourceactionOrderby property. */
    private java.lang.Long sourceactionOrderby;

    /**
     * Simple constructor of AbstractSourceactionconfig instances.
     */
    public AbstractSourceactionconfig()
    {
    }

    /**
     * Constructor of AbstractSourceactionconfig instances given a simple primary key.
     * @param id
     */
    public AbstractSourceactionconfig(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the SOURCEACTION_TYPEFLAG column.
     * @return java.lang.String
     */
    public java.lang.String getSourceactionTypeflag()
    {
        return this.sourceactionTypeflag;
    }

    /**
     * Set the value of the SOURCEACTION_TYPEFLAG column.
     * @param sourceactionTypeflag
     */
    public void setSourceactionTypeflag(java.lang.String sourceactionTypeflag)
    {
        this.sourceactionTypeflag = sourceactionTypeflag;
    }

    /**
     * Return the value of the SOURCEACTION_FIELDVALUE column.
     * @return java.lang.String
     */
    public java.lang.String getSourceactionFieldvalue()
    {
        return this.sourceactionFieldvalue;
    }

    /**
     * Set the value of the SOURCEACTION_FIELDVALUE column.
     * @param sourceactionFieldvalue
     */
    public void setSourceactionFieldvalue(java.lang.String sourceactionFieldvalue)
    {
        this.sourceactionFieldvalue = sourceactionFieldvalue;
    }

    /**
     * Return the value of the SOURCEACTION_NUMVALUE column.
     * @return java.lang.String
     */
    public java.lang.String getSourceactionNumvalue()
    {
        return this.sourceactionNumvalue;
    }

    /**
     * Set the value of the SOURCEACTION_NUMVALUE column.
     * @param sourceactionNumvalue
     */
    public void setSourceactionNumvalue(java.lang.String sourceactionNumvalue)
    {
        this.sourceactionNumvalue = sourceactionNumvalue;
    }

    /**
     * Return the value of the SOURCEACTION_ORDERBY column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceactionOrderby()
    {
        return this.sourceactionOrderby;
    }

    /**
     * Set the value of the SOURCEACTION_ORDERBY column.
     * @param sourceactionOrderby
     */
    public void setSourceactionOrderby(java.lang.Long sourceactionOrderby)
    {
        this.sourceactionOrderby = sourceactionOrderby;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Sourceactionconfig))
            return false;
        Sourceactionconfig that = (Sourceactionconfig) rhs;
        if (this.getId() == null || that.getId() == null)
            return false;
        return (this.getId().equals(that.getId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
