/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 10 14:24:44 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.source.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the SOURCEATTRIBUTECONFIG table. 
 * You can customize the behavior of this class by editing the class, {@link Sourceattributeconfig()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractSourceattributeconfig 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long sourceattcfgId;

    /** The value of the simple sourceattcfgTypeflag property. */
    private java.lang.String sourceattcfgTypeflag;

    /** The value of the simple sourceattcfgCnname property. */
    private java.lang.String sourceattcfgCnname;

    /** The value of the simple sourceattcfgEnname property. */
    private java.lang.String sourceattcfgEnname;

    /** The value of the simple sourceattcfgType property. */
    private java.lang.String sourceattcfgType;

    /** The value of the simple sourceattcfgOrderby property. */
    private java.lang.Long sourceattcfgOrderby;

    /** The value of the simple sourceattcfgDesc property. */
    private java.lang.String sourceattcfgDesc;

    /**
     * Simple constructor of AbstractSourceattributeconfig instances.
     */
    public AbstractSourceattributeconfig()
    {
    }

    /**
     * Constructor of AbstractSourceattributeconfig instances given a simple primary key.
     * @param sourceattcfgId
     */
    public AbstractSourceattributeconfig(java.lang.Long sourceattcfgId)
    {
        this.setSourceattcfgId(sourceattcfgId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceattcfgId()
    {
        return sourceattcfgId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param sourceattcfgId
     */
    public void setSourceattcfgId(java.lang.Long sourceattcfgId)
    {
        this.hashValue = 0;
        this.sourceattcfgId = sourceattcfgId;
    }

    /**
     * Return the value of the SOURCEATTCFG_TYPEFLAG column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattcfgTypeflag()
    {
        return this.sourceattcfgTypeflag;
    }

    /**
     * Set the value of the SOURCEATTCFG_TYPEFLAG column.
     * @param sourceattcfgTypeflag
     */
    public void setSourceattcfgTypeflag(java.lang.String sourceattcfgTypeflag)
    {
        this.sourceattcfgTypeflag = sourceattcfgTypeflag;
    }

    /**
     * Return the value of the SOURCEATTCFG_CNNAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattcfgCnname()
    {
        return this.sourceattcfgCnname;
    }

    /**
     * Set the value of the SOURCEATTCFG_CNNAME column.
     * @param sourceattcfgCnname
     */
    public void setSourceattcfgCnname(java.lang.String sourceattcfgCnname)
    {
        this.sourceattcfgCnname = sourceattcfgCnname;
    }

    /**
     * Return the value of the SOURCEATTCFG_ENNAME column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattcfgEnname()
    {
        return this.sourceattcfgEnname;
    }

    /**
     * Set the value of the SOURCEATTCFG_ENNAME column.
     * @param sourceattcfgEnname
     */
    public void setSourceattcfgEnname(java.lang.String sourceattcfgEnname)
    {
        this.sourceattcfgEnname = sourceattcfgEnname;
    }

    /**
     * Return the value of the SOURCEATTCFG_TYPE column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattcfgType()
    {
        return this.sourceattcfgType;
    }

    /**
     * Set the value of the SOURCEATTCFG_TYPE column.
     * @param sourceattcfgType
     */
    public void setSourceattcfgType(java.lang.String sourceattcfgType)
    {
        this.sourceattcfgType = sourceattcfgType;
    }

    /**
     * Return the value of the SOURCEATTCFG_ORDERBY column.
     * @return java.lang.Long
     */
    public java.lang.Long getSourceattcfgOrderby()
    {
        return this.sourceattcfgOrderby;
    }

    /**
     * Set the value of the SOURCEATTCFG_ORDERBY column.
     * @param sourceattcfgOrderby
     */
    public void setSourceattcfgOrderby(java.lang.Long sourceattcfgOrderby)
    {
        this.sourceattcfgOrderby = sourceattcfgOrderby;
    }

    /**
     * Return the value of the SOURCEATTCFG_DESC column.
     * @return java.lang.String
     */
    public java.lang.String getSourceattcfgDesc()
    {
        return this.sourceattcfgDesc;
    }

    /**
     * Set the value of the SOURCEATTCFG_DESC column.
     * @param sourceattcfgDesc
     */
    public void setSourceattcfgDesc(java.lang.String sourceattcfgDesc)
    {
        this.sourceattcfgDesc = sourceattcfgDesc;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Sourceattributeconfig))
            return false;
        Sourceattributeconfig that = (Sourceattributeconfig) rhs;
        if (this.getSourceattcfgId() == null || that.getSourceattcfgId() == null)
            return false;
        return (this.getSourceattcfgId().equals(that.getSourceattcfgId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int sourceattcfgIdValue = this.getSourceattcfgId() == null ? 0 : this.getSourceattcfgId().hashCode();
            result = result * 37 + sourceattcfgIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
