/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Jan 29 10:11:25 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.config.source.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the PORTALET_SUBSCIBE table. 
 * You can customize the behavior of this class by editing the class, {@link PortaletSubscibe()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractPortaletSubscibe 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long portaletId;

    /** The value of the simple portaletParentid property. */
    private java.lang.Long portaletParentid;

    /** The value of the simple portaletUserloginname property. */
    private java.lang.String portaletUserloginname;

    /** The value of the simple portaletPortalsourceid property. */
    private java.lang.Long portaletPortalsourceid;

    /** The value of the simple portaletContentsourceid property. */
    private java.lang.Long portaletContentsourceid;

    /** The value of the simple portaletOrderby property. */
    private java.lang.Long portaletOrderby;

    /** The value of the simple note property. */
    private java.lang.String note;

    /**
     * Simple constructor of AbstractPortaletSubscibe instances.
     */
    public AbstractPortaletSubscibe()
    {
    }

    /**
     * Constructor of AbstractPortaletSubscibe instances given a simple primary key.
     * @param portaletId
     */
    public AbstractPortaletSubscibe(java.lang.Long portaletId)
    {
        this.setPortaletId(portaletId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getPortaletId()
    {
        return portaletId;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param portaletId
     */
    public void setPortaletId(java.lang.Long portaletId)
    {
        this.hashValue = 0;
        this.portaletId = portaletId;
    }

    /**
     * Return the value of the PORTALET_PARENTID column.
     * @return java.lang.Long
     */
    public java.lang.Long getPortaletParentid()
    {
        return this.portaletParentid;
    }

    /**
     * Set the value of the PORTALET_PARENTID column.
     * @param portaletParentid
     */
    public void setPortaletParentid(java.lang.Long portaletParentid)
    {
        this.portaletParentid = portaletParentid;
    }

    /**
     * Return the value of the PORTALET_USERLOGINNAME column.
     * @return java.lang.String
     */
    public java.lang.String getPortaletUserloginname()
    {
        return this.portaletUserloginname;
    }

    /**
     * Set the value of the PORTALET_USERLOGINNAME column.
     * @param portaletUserloginname
     */
    public void setPortaletUserloginname(java.lang.String portaletUserloginname)
    {
        this.portaletUserloginname = portaletUserloginname;
    }

    /**
     * Return the value of the PORTALET_PORTALSOURCEID column.
     * @return java.lang.Long
     */
    public java.lang.Long getPortaletPortalsourceid()
    {
        return this.portaletPortalsourceid;
    }

    /**
     * Set the value of the PORTALET_PORTALSOURCEID column.
     * @param portaletPortalsourceid
     */
    public void setPortaletPortalsourceid(java.lang.Long portaletPortalsourceid)
    {
        this.portaletPortalsourceid = portaletPortalsourceid;
    }

    /**
     * Return the value of the PORTALET_CONTENTSOURCEID column.
     * @return java.lang.Long
     */
    public java.lang.Long getPortaletContentsourceid()
    {
        return this.portaletContentsourceid;
    }

    /**
     * Set the value of the PORTALET_CONTENTSOURCEID column.
     * @param portaletContentsourceid
     */
    public void setPortaletContentsourceid(java.lang.Long portaletContentsourceid)
    {
        this.portaletContentsourceid = portaletContentsourceid;
    }

    /**
     * Return the value of the PORTALET_ORDERBY column.
     * @return java.lang.Long
     */
    public java.lang.Long getPortaletOrderby()
    {
        return this.portaletOrderby;
    }

    /**
     * Set the value of the PORTALET_ORDERBY column.
     * @param portaletOrderby
     */
    public void setPortaletOrderby(java.lang.Long portaletOrderby)
    {
        this.portaletOrderby = portaletOrderby;
    }

    /**
     * Return the value of the NOTE column.
     * @return java.lang.String
     */
    public java.lang.String getNote()
    {
        return this.note;
    }

    /**
     * Set the value of the NOTE column.
     * @param note
     */
    public void setNote(java.lang.String note)
    {
        this.note = note;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof PortaletSubscibe))
            return false;
        PortaletSubscibe that = (PortaletSubscibe) rhs;
        if (this.getPortaletId() == null || that.getPortaletId() == null)
            return false;
        return (this.getPortaletId().equals(that.getPortaletId()));
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int portaletIdValue = this.getPortaletId() == null ? 0 : this.getPortaletId().hashCode();
            result = result * 37 + portaletIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
