/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Tue Oct 31 14:41:48 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.role.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T92 table. 
 * You can customize the behavior of this class by editing the class, {@link T92()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT92 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c610000006 property. */
    private java.lang.String c610000006;

    /** The value of the simple c610000007 property. */
    private java.lang.String c610000007;

    /** The value of the simple c610000008 property. */
    private java.lang.String c610000008;

    /** The value of the simple c610000009 property. */
    private java.lang.String c610000009;

    /** The value of the simple c610000011 property. */
    private java.lang.String c610000011;

    /** The value of the simple c610000012 property. */
    private java.lang.String c610000012;

    /** The value of the simple c610000014 property. */
    private java.lang.String c610000014;

    /** The value of the simple c610000018 property. */
    private java.lang.String c610000018;

    /** The value of the simple c610000019 property. */
    private java.lang.String c610000019;

    /** The value of the simple c610000010 property. */
    private java.lang.String c610000010;

    /** The value of the simple c610000015 property. */
    private java.lang.Long c610000015;

    /**
     * Simple constructor of AbstractT92 instances.
     */
    public AbstractT92()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C610000006 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000006()
    {
        return this.c610000006;
    }

    /**
     * Set the value of the C610000006 column.
     * @param c610000006
     */
    public void setC610000006(java.lang.String c610000006)
    {
        this.c610000006 = c610000006;
    }

    /**
     * Return the value of the C610000007 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000007()
    {
        return this.c610000007;
    }

    /**
     * Set the value of the C610000007 column.
     * @param c610000007
     */
    public void setC610000007(java.lang.String c610000007)
    {
        this.c610000007 = c610000007;
    }

    /**
     * Return the value of the C610000008 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000008()
    {
        return this.c610000008;
    }

    /**
     * Set the value of the C610000008 column.
     * @param c610000008
     */
    public void setC610000008(java.lang.String c610000008)
    {
        this.c610000008 = c610000008;
    }

    /**
     * Return the value of the C610000009 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000009()
    {
        return this.c610000009;
    }

    /**
     * Set the value of the C610000009 column.
     * @param c610000009
     */
    public void setC610000009(java.lang.String c610000009)
    {
        this.c610000009 = c610000009;
    }

    /**
     * Return the value of the C610000011 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000011()
    {
        return this.c610000011;
    }

    /**
     * Set the value of the C610000011 column.
     * @param c610000011
     */
    public void setC610000011(java.lang.String c610000011)
    {
        this.c610000011 = c610000011;
    }

    /**
     * Return the value of the C610000012 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000012()
    {
        return this.c610000012;
    }

    /**
     * Set the value of the C610000012 column.
     * @param c610000012
     */
    public void setC610000012(java.lang.String c610000012)
    {
        this.c610000012 = c610000012;
    }

    /**
     * Return the value of the C610000014 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000014()
    {
        return this.c610000014;
    }

    /**
     * Set the value of the C610000014 column.
     * @param c610000014
     */
    public void setC610000014(java.lang.String c610000014)
    {
        this.c610000014 = c610000014;
    }

    /**
     * Return the value of the C610000018 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000018()
    {
        return this.c610000018;
    }

    /**
     * Set the value of the C610000018 column.
     * @param c610000018
     */
    public void setC610000018(java.lang.String c610000018)
    {
        this.c610000018 = c610000018;
    }

    /**
     * Return the value of the C610000019 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000019()
    {
        return this.c610000019;
    }

    /**
     * Set the value of the C610000019 column.
     * @param c610000019
     */
    public void setC610000019(java.lang.String c610000019)
    {
        this.c610000019 = c610000019;
    }

    /**
     * Return the value of the C610000010 column.
     * @return java.lang.String
     */
    public java.lang.String getC610000010()
    {
        return this.c610000010;
    }

    /**
     * Set the value of the C610000010 column.
     * @param c610000010
     */
    public void setC610000010(java.lang.String c610000010)
    {
        this.c610000010 = c610000010;
    }

    /**
     * Return the value of the C610000015 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC610000015()
    {
        return this.c610000015;
    }

    /**
     * Set the value of the C610000015 column.
     * @param c610000015
     */
    public void setC610000015(java.lang.Long c610000015)
    {
        this.c610000015 = c610000015;
    }
}
