/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 06 19:43:24 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.templet.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T238 table. 
 * You can customize the behavior of this class by editing the class, {@link T238()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT602 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c670000001 property. */
    private java.lang.String c670000001;

    /** The value of the simple c670000002 property. */
    private java.lang.String c670000002;

    /** The value of the simple c670000003 property. */
    private java.lang.String c670000003;
    
    /** The value of the simple c670000004 property. */
    private java.lang.Long c670000004;

    /** The value of the simple c670000005 property. */
    private java.lang.String c670000005;

    /** The value of the simple c670000006 property. */
    private java.lang.String c670000006;

    /** The value of the simple c670000007 property. */
    private java.lang.String c670000007;

    /** The value of the simple c670000008 property. */
    private java.lang.Long c670000008;
    
    /** The value of the simple c670000009 property. */
    private java.lang.String c670000009;
    
    /** The value of the simple c670000010 property. */
    private java.lang.String c670000010;
    
    /** The value of the simple c670000011 property. */
    private java.lang.String c670000011;
    
    /** The value of the simple c670000012 property. */
    private java.lang.String c670000012;
    
    /** The value of the simple c670000013 property. */
    private java.lang.String c670000013;
   
    /**
     * Simple constructor of AbstractT238 instances.
     */
    public AbstractT602()
    {
    }

	public java.lang.String getC1() {
		return c1;
	}

	public void setC1(java.lang.String c1) {
		this.c1 = c1;
	}

	public java.lang.String getC2() {
		return c2;
	}

	public void setC2(java.lang.String c2) {
		this.c2 = c2;
	}

	public java.lang.Long getC3() {
		return c3;
	}

	public void setC3(java.lang.Long c3) {
		this.c3 = c3;
	}

	public java.lang.String getC4() {
		return c4;
	}

	public void setC4(java.lang.String c4) {
		this.c4 = c4;
	}

	public java.lang.String getC5() {
		return c5;
	}

	public void setC5(java.lang.String c5) {
		this.c5 = c5;
	}

	public java.lang.Long getC6() {
		return c6;
	}

	public void setC6(java.lang.Long c6) {
		this.c6 = c6;
	}

	public java.lang.Long getC7() {
		return c7;
	}

	public void setC7(java.lang.Long c7) {
		this.c7 = c7;
	}

	public java.lang.String getC8() {
		return c8;
	}

	public void setC8(java.lang.String c8) {
		this.c8 = c8;
	}

	public java.lang.String getC670000001() {
		return c670000001;
	}

	public void setC670000001(java.lang.String c670000001) {
		this.c670000001 = c670000001;
	}

	public java.lang.String getC670000002() {
		return c670000002;
	}

	public void setC670000002(java.lang.String c670000002) {
		this.c670000002 = c670000002;
	}

	public java.lang.String getC670000003() {
		return c670000003;
	}

	public void setC670000003(java.lang.String c670000003) {
		this.c670000003 = c670000003;
	}

	public java.lang.Long getC670000004() {
		return c670000004;
	}

	public void setC670000004(java.lang.Long c670000004) {
		this.c670000004 = c670000004;
	}

	public java.lang.String getC670000005() {
		return c670000005;
	}

	public void setC670000005(java.lang.String c670000005) {
		this.c670000005 = c670000005;
	}

	public java.lang.String getC670000006() {
		return c670000006;
	}

	public void setC670000006(java.lang.String c670000006) {
		this.c670000006 = c670000006;
	}

	public java.lang.String getC670000007() {
		return c670000007;
	}

	public void setC670000007(java.lang.String c670000007) {
		this.c670000007 = c670000007;
	}

	public java.lang.Long getC670000008() {
		return c670000008;
	}

	public void setC670000008(java.lang.Long c670000008) {
		this.c670000008 = c670000008;
	}

	public java.lang.String getC670000009() {
		return c670000009;
	}

	public void setC670000009(java.lang.String c670000009) {
		this.c670000009 = c670000009;
	}

	public java.lang.String getC670000010() {
		return c670000010;
	}

	public void setC670000010(java.lang.String c670000010) {
		this.c670000010 = c670000010;
	}

	public java.lang.String getC670000011() {
		return c670000011;
	}

	public void setC670000011(java.lang.String c670000011) {
		this.c670000011 = c670000011;
	}

	public java.lang.String getC670000012() {
		return c670000012;
	}

	public void setC670000012(java.lang.String c670000012) {
		this.c670000012 = c670000012;
	}

	public java.lang.String getC670000013() {
		return c670000013;
	}

	public void setC670000013(java.lang.String c670000013) {
		this.c670000013 = c670000013;
	}

   
}
