/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Dec 25 14:49:15 CST 2006 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.templet.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T149 table. 
 * You can customize the behavior of this class by editing the class, {@link T149()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT149 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c660000006 property. */
    private java.lang.String c660000006;

    /** The value of the simple c660000007 property. */
    private java.lang.String c660000007;

    /** The value of the simple c660000008 property. */
    private java.lang.String c660000008;

    /** The value of the simple c660000009 property. */
    private java.lang.String c660000009;

    /** The value of the simple c660000010 property. */
    private java.lang.String c660000010;

    /** The value of the simple c660000011 property. */
    private java.lang.String c660000011;

    /** The value of the simple c660000012 property. */
    private java.lang.String c660000012;

    /** The value of the simple c660000013 property. */
    private java.lang.String c660000013;

    /**
     * Simple constructor of AbstractT149 instances.
     */
    public AbstractT149()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C660000006 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000006()
    {
        return this.c660000006;
    }

    /**
     * Set the value of the C660000006 column.
     * @param c660000006
     */
    public void setC660000006(java.lang.String c660000006)
    {
        this.c660000006 = c660000006;
    }

    /**
     * Return the value of the C660000007 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000007()
    {
        return this.c660000007;
    }

    /**
     * Set the value of the C660000007 column.
     * @param c660000007
     */
    public void setC660000007(java.lang.String c660000007)
    {
        this.c660000007 = c660000007;
    }

    /**
     * Return the value of the C660000008 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000008()
    {
        return this.c660000008;
    }

    /**
     * Set the value of the C660000008 column.
     * @param c660000008
     */
    public void setC660000008(java.lang.String c660000008)
    {
        this.c660000008 = c660000008;
    }

    /**
     * Return the value of the C660000009 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000009()
    {
        return this.c660000009;
    }

    /**
     * Set the value of the C660000009 column.
     * @param c660000009
     */
    public void setC660000009(java.lang.String c660000009)
    {
        this.c660000009 = c660000009;
    }

    /**
     * Return the value of the C660000010 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000010()
    {
        return this.c660000010;
    }

    /**
     * Set the value of the C660000010 column.
     * @param c660000010
     */
    public void setC660000010(java.lang.String c660000010)
    {
        this.c660000010 = c660000010;
    }

    /**
     * Return the value of the C660000011 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000011()
    {
        return this.c660000011;
    }

    /**
     * Set the value of the C660000011 column.
     * @param c660000011
     */
    public void setC660000011(java.lang.String c660000011)
    {
        this.c660000011 = c660000011;
    }

    /**
     * Return the value of the C660000012 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000012()
    {
        return this.c660000012;
    }

    /**
     * Set the value of the C660000012 column.
     * @param c660000012
     */
    public void setC660000012(java.lang.String c660000012)
    {
        this.c660000012 = c660000012;
    }

    /**
     * Return the value of the C660000013 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000013()
    {
        return this.c660000013;
    }

    /**
     * Set the value of the C660000013 column.
     * @param c660000013
     */
    public void setC660000013(java.lang.String c660000013)
    {
        this.c660000013 = c660000013;
    }
}
