/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 06 19:43:24 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.templet.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T606 table. 
 * You can customize the behavior of this class by editing the class, {@link T606()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT606 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c660000001 property. */
    private java.lang.String c660000001;

    /** The value of the simple c660000002 property. */
    private java.lang.String c660000002;
    
    /** The value of the simple c660000003 property. */
    private java.lang.String c660000003;
    
    /** The value of the simple c660000004 property. */
    private java.lang.String c660000004;
    
    /** The value of the simple c660000005 property. */
    private java.lang.String c660000005;
    
    /** The value of the simple c660000006 property. */
    private java.lang.String c660000006;
    
    /** The value of the simple c660000007 property. */
    private java.lang.String c660000007;
    
    /** The value of the simple c660000008 property. */
    private java.lang.String c660000008;
    
    /** The value of the simple c660000009 property. */
    private java.lang.String c660000009;
    
    /** The value of the simple c660000010 property. */
    private java.lang.String c660000010;
    
    /** The value of the simple c660000011 property. */
    private java.lang.String c660000011;
    
    /** The value of the simple c660000012 property. */
    private java.lang.String c660000012;
    
    /** The value of the simple c660000013 property. */
    private java.lang.String c660000013;
    
    /** The value of the simple c660000014 property. */
    private java.lang.String c660000014;
    
    /** The value of the simple c660000015 property. */
    private java.lang.String c660000015;
    
    /** The value of the simple c660000016 property. */
    private java.lang.String c660000016;
    
    /** The value of the simple c660000017 property. */
    private java.lang.String c660000017;
    
    /** The value of the simple c660000018 property. */
    private java.lang.String c660000018;
    
    /** The value of the simple c660000019 property. */
    private java.lang.Long c660000019;
    
    /** The value of the simple c660000020 property. */
    private java.lang.String c660000020;
    
    /** The value of the simple c660000021 property. */
    private java.lang.String c660000021;
    
    /** The value of the simple c660000022 property. */
    private java.lang.String c660000022;
    
    /** The value of the simple c660000023 property. */
    private java.lang.String c660000023;

    /**
     * Simple constructor of AbstractT606 instances.
     */
    public AbstractT606()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

	public java.lang.String getC660000001() {
		return c660000001;
	}

	public void setC660000001(java.lang.String c660000001) {
		this.c660000001 = c660000001;
	}

	public java.lang.String getC660000002() {
		return c660000002;
	}

	public void setC660000002(java.lang.String c660000002) {
		this.c660000002 = c660000002;
	}

	public java.lang.String getC660000003() {
		return c660000003;
	}

	public void setC660000003(java.lang.String c660000003) {
		this.c660000003 = c660000003;
	}

	public java.lang.String getC660000004() {
		return c660000004;
	}

	public void setC660000004(java.lang.String c660000004) {
		this.c660000004 = c660000004;
	}

	public java.lang.String getC660000005() {
		return c660000005;
	}

	public void setC660000005(java.lang.String c660000005) {
		this.c660000005 = c660000005;
	}

	public java.lang.String getC660000006() {
		return c660000006;
	}

	public void setC660000006(java.lang.String c660000006) {
		this.c660000006 = c660000006;
	}

	public java.lang.String getC660000007() {
		return c660000007;
	}

	public void setC660000007(java.lang.String c660000007) {
		this.c660000007 = c660000007;
	}

	public java.lang.String getC660000008() {
		return c660000008;
	}

	public void setC660000008(java.lang.String c660000008) {
		this.c660000008 = c660000008;
	}

	public java.lang.String getC660000009() {
		return c660000009;
	}

	public void setC660000009(java.lang.String c660000009) {
		this.c660000009 = c660000009;
	}

	public java.lang.String getC660000010() {
		return c660000010;
	}

	public void setC660000010(java.lang.String c660000010) {
		this.c660000010 = c660000010;
	}

	public java.lang.String getC660000011() {
		return c660000011;
	}

	public void setC660000011(java.lang.String c660000011) {
		this.c660000011 = c660000011;
	}

	public java.lang.String getC660000012() {
		return c660000012;
	}

	public void setC660000012(java.lang.String c660000012) {
		this.c660000012 = c660000012;
	}

	public java.lang.String getC660000013() {
		return c660000013;
	}

	public void setC660000013(java.lang.String c660000013) {
		this.c660000013 = c660000013;
	}

	public java.lang.String getC660000014() {
		return c660000014;
	}

	public void setC660000014(java.lang.String c660000014) {
		this.c660000014 = c660000014;
	}

	public java.lang.String getC660000015() {
		return c660000015;
	}

	public void setC660000015(java.lang.String c660000015) {
		this.c660000015 = c660000015;
	}

	public java.lang.String getC660000016() {
		return c660000016;
	}

	public void setC660000016(java.lang.String c660000016) {
		this.c660000016 = c660000016;
	}

	public java.lang.String getC660000017() {
		return c660000017;
	}

	public void setC660000017(java.lang.String c660000017) {
		this.c660000017 = c660000017;
	}

	public java.lang.String getC660000018() {
		return c660000018;
	}

	public void setC660000018(java.lang.String c660000018) {
		this.c660000018 = c660000018;
	}

	public java.lang.Long getC660000019() {
		return c660000019;
	}

	public void setC660000019(java.lang.Long c660000019) {
		this.c660000019 = c660000019;
	}

	public java.lang.String getC660000020() {
		return c660000020;
	}

	public void setC660000020(java.lang.String c660000020) {
		this.c660000020 = c660000020;
	}

	public java.lang.String getC660000021() {
		return c660000021;
	}

	public void setC660000021(java.lang.String c660000021) {
		this.c660000021 = c660000021;
	}

	public java.lang.String getC660000022() {
		return c660000022;
	}

	public void setC660000022(java.lang.String c660000022) {
		this.c660000022 = c660000022;
	}

	public java.lang.String getC660000023() {
		return c660000023;
	}

	public void setC660000023(java.lang.String c660000023) {
		this.c660000023 = c660000023;
	}

}
