/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 06 19:43:24 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.templet.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T238 table. 
 * You can customize the behavior of this class by editing the class, {@link T238()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT238 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c660000026 property. */
    private java.lang.String c660000026;

    /** The value of the simple c660000027 property. */
    private java.lang.String c660000027;

    /** The value of the simple c660000028 property. */
    private java.lang.String c660000028;

    /** The value of the simple c660000031 property. */
    private java.lang.String c660000031;

    /** The value of the simple c660000032 property. */
    private java.lang.String c660000032;

    /** The value of the simple c660000033 property. */
    private java.lang.String c660000033;

    /** The value of the simple c660000030 property. */
    private java.lang.Long c660000030;

    /**
     * Simple constructor of AbstractT238 instances.
     */
    public AbstractT238()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

    /**
     * Return the value of the C660000026 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000026()
    {
        return this.c660000026;
    }

    /**
     * Set the value of the C660000026 column.
     * @param c660000026
     */
    public void setC660000026(java.lang.String c660000026)
    {
        this.c660000026 = c660000026;
    }

    /**
     * Return the value of the C660000027 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000027()
    {
        return this.c660000027;
    }

    /**
     * Set the value of the C660000027 column.
     * @param c660000027
     */
    public void setC660000027(java.lang.String c660000027)
    {
        this.c660000027 = c660000027;
    }

    /**
     * Return the value of the C660000028 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000028()
    {
        return this.c660000028;
    }

    /**
     * Set the value of the C660000028 column.
     * @param c660000028
     */
    public void setC660000028(java.lang.String c660000028)
    {
        this.c660000028 = c660000028;
    }

    /**
     * Return the value of the C660000031 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000031()
    {
        return this.c660000031;
    }

    /**
     * Set the value of the C660000031 column.
     * @param c660000031
     */
    public void setC660000031(java.lang.String c660000031)
    {
        this.c660000031 = c660000031;
    }

    /**
     * Return the value of the C660000032 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000032()
    {
        return this.c660000032;
    }

    /**
     * Set the value of the C660000032 column.
     * @param c660000032
     */
    public void setC660000032(java.lang.String c660000032)
    {
        this.c660000032 = c660000032;
    }

    /**
     * Return the value of the C660000033 column.
     * @return java.lang.String
     */
    public java.lang.String getC660000033()
    {
        return this.c660000033;
    }

    /**
     * Set the value of the C660000033 column.
     * @param c660000033
     */
    public void setC660000033(java.lang.String c660000033)
    {
        this.c660000033 = c660000033;
    }

    /**
     * Return the value of the C660000030 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC660000030()
    {
        return this.c660000030;
    }

    /**
     * Set the value of the C660000030 column.
     * @param c660000030
     */
    public void setC660000030(java.lang.Long c660000030)
    {
        this.c660000030 = c660000030;
    }
}
