/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Jan 06 19:43:24 CST 2007 by MyEclipse Hibernate Tool.
 */
package cn.com.ultrapower.eoms.user.authorization.templet.hibernate.po;

import java.io.Serializable;

/**
 * A class that represents a row in the T550 table. 
 * You can customize the behavior of this class by editing the class, {@link T550()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractT550 
    implements Serializable
{

    /** The value of the simple c1 property. */
    private java.lang.String c1;

    /** The value of the simple c2 property. */
    private java.lang.String c2;

    /** The value of the simple c3 property. */
    private java.lang.Long c3;

    /** The value of the simple c4 property. */
    private java.lang.String c4;

    /** The value of the simple c5 property. */
    private java.lang.String c5;

    /** The value of the simple c6 property. */
    private java.lang.Long c6;

    /** The value of the simple c7 property. */
    private java.lang.Long c7;

    /** The value of the simple c8 property. */
    private java.lang.String c8;

    /** The value of the simple c650000001 property. */
    private java.lang.String c650000001;

    /** The value of the simple c650000002 property. */
    private java.lang.String c650000002;
    
    /** The value of the simple c650000003 property. */
    private java.lang.String c650000003;
    
    /** The value of the simple c650000004 property. */
    private java.lang.String c650000004;
    
    /** The value of the simple c650000005 property. */
    private java.lang.String c650000005;
    
    /** The value of the simple c650000006 property. */
    private java.lang.String c650000006;
    
    /** The value of the simple c650000007 property. */
    private java.lang.String c650000007;
    
    /** The value of the simple c650000008 property. */
    private java.lang.String c650000008;
    
    /** The value of the simple c650000009 property. */
    private java.lang.String c650000009;
    
    /** The value of the simple c650000010 property. */
    private java.lang.String c650000010;
    
    /** The value of the simple c650000011 property. */
    private java.lang.String c650000011;
    
    /** The value of the simple c650000012 property. */
    private java.lang.String c650000012;
    
    /** The value of the simple c650000013 property. */
    private java.lang.String c650000013;
    
    /** The value of the simple c650000014 property. */
    private java.lang.String c650000014;
    
    /** The value of the simple c650000015 property. */
    private java.lang.String c650000015;
    
    /** The value of the simple c650000016 property. */
    private java.lang.String c650000016;
    
    /** The value of the simple c650000017 property. */
    private java.lang.String c650000017;
    
    /** The value of the simple c650000018 property. */
    private java.lang.String c650000018;

    /**
     * Simple constructor of AbstractT550 instances.
     */
    public AbstractT550()
    {
    }

    /**
     * Return the value of the C1 column.
     * @return java.lang.String
     */
    public java.lang.String getC1()
    {
        return this.c1;
    }

    /**
     * Set the value of the C1 column.
     * @param c1
     */
    public void setC1(java.lang.String c1)
    {
        this.c1 = c1;
    }

    /**
     * Return the value of the C2 column.
     * @return java.lang.String
     */
    public java.lang.String getC2()
    {
        return this.c2;
    }

    /**
     * Set the value of the C2 column.
     * @param c2
     */
    public void setC2(java.lang.String c2)
    {
        this.c2 = c2;
    }

    /**
     * Return the value of the C3 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC3()
    {
        return this.c3;
    }

    /**
     * Set the value of the C3 column.
     * @param c3
     */
    public void setC3(java.lang.Long c3)
    {
        this.c3 = c3;
    }

    /**
     * Return the value of the C4 column.
     * @return java.lang.String
     */
    public java.lang.String getC4()
    {
        return this.c4;
    }

    /**
     * Set the value of the C4 column.
     * @param c4
     */
    public void setC4(java.lang.String c4)
    {
        this.c4 = c4;
    }

    /**
     * Return the value of the C5 column.
     * @return java.lang.String
     */
    public java.lang.String getC5()
    {
        return this.c5;
    }

    /**
     * Set the value of the C5 column.
     * @param c5
     */
    public void setC5(java.lang.String c5)
    {
        this.c5 = c5;
    }

    /**
     * Return the value of the C6 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC6()
    {
        return this.c6;
    }

    /**
     * Set the value of the C6 column.
     * @param c6
     */
    public void setC6(java.lang.Long c6)
    {
        this.c6 = c6;
    }

    /**
     * Return the value of the C7 column.
     * @return java.lang.Long
     */
    public java.lang.Long getC7()
    {
        return this.c7;
    }

    /**
     * Set the value of the C7 column.
     * @param c7
     */
    public void setC7(java.lang.Long c7)
    {
        this.c7 = c7;
    }

    /**
     * Return the value of the C8 column.
     * @return java.lang.String
     */
    public java.lang.String getC8()
    {
        return this.c8;
    }

    /**
     * Set the value of the C8 column.
     * @param c8
     */
    public void setC8(java.lang.String c8)
    {
        this.c8 = c8;
    }

	public java.lang.String getC650000001() {
		return c650000001;
	}

	public void setC650000001(java.lang.String c650000001) {
		this.c650000001 = c650000001;
	}

	public java.lang.String getC650000002() {
		return c650000002;
	}

	public void setC650000002(java.lang.String c650000002) {
		this.c650000002 = c650000002;
	}

	public java.lang.String getC650000003() {
		return c650000003;
	}

	public void setC650000003(java.lang.String c650000003) {
		this.c650000003 = c650000003;
	}

	public java.lang.String getC650000004() {
		return c650000004;
	}

	public void setC650000004(java.lang.String c650000004) {
		this.c650000004 = c650000004;
	}

	public java.lang.String getC650000005() {
		return c650000005;
	}

	public void setC650000005(java.lang.String c650000005) {
		this.c650000005 = c650000005;
	}

	public java.lang.String getC650000006() {
		return c650000006;
	}

	public void setC650000006(java.lang.String c650000006) {
		this.c650000006 = c650000006;
	}

	public java.lang.String getC650000007() {
		return c650000007;
	}

	public void setC650000007(java.lang.String c650000007) {
		this.c650000007 = c650000007;
	}

	public java.lang.String getC650000008() {
		return c650000008;
	}

	public void setC650000008(java.lang.String c650000008) {
		this.c650000008 = c650000008;
	}

	public java.lang.String getC650000009() {
		return c650000009;
	}

	public void setC650000009(java.lang.String c650000009) {
		this.c650000009 = c650000009;
	}

	public java.lang.String getC650000010() {
		return c650000010;
	}

	public void setC650000010(java.lang.String c650000010) {
		this.c650000010 = c650000010;
	}

	public java.lang.String getC650000011() {
		return c650000011;
	}

	public void setC650000011(java.lang.String c650000011) {
		this.c650000011 = c650000011;
	}

	public java.lang.String getC650000012() {
		return c650000012;
	}

	public void setC650000012(java.lang.String c650000012) {
		this.c650000012 = c650000012;
	}

	public java.lang.String getC650000013() {
		return c650000013;
	}

	public void setC650000013(java.lang.String c650000013) {
		this.c650000013 = c650000013;
	}

	public java.lang.String getC650000014() {
		return c650000014;
	}

	public void setC650000014(java.lang.String c650000014) {
		this.c650000014 = c650000014;
	}

	public java.lang.String getC650000015() {
		return c650000015;
	}

	public void setC650000015(java.lang.String c650000015) {
		this.c650000015 = c650000015;
	}

	public java.lang.String getC650000016() {
		return c650000016;
	}

	public void setC650000016(java.lang.String c650000016) {
		this.c650000016 = c650000016;
	}

	public java.lang.String getC650000017() {
		return c650000017;
	}

	public void setC650000017(java.lang.String c650000017) {
		this.c650000017 = c650000017;
	}

	public java.lang.String getC650000018() {
		return c650000018;
	}

	public void setC650000018(java.lang.String c650000018) {
		this.c650000018 = c650000018;
	}

    
}
