package cn.com.ultrapower.eoms.user.config.grade.hibernate.po;
// Generated by MyEclipse - Hibernate Tools



/**
 * Depgradeconfig generated by MyEclipse - Hibernate Tools
 */
public class Depgradeconfig extends AbstractDepgradeconfig implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Depgradeconfig() {
    }

    
    /** full constructor */
    public Depgradeconfig(String depgradeconfigDep, Double depgradeconfigGradvalue, Long depgradeconfigAffectbusiness) {
        super(depgradeconfigDep, depgradeconfigGradvalue, depgradeconfigAffectbusiness);        
    }
   
}
