package cn.com.ultrapower.eoms.user.config.grade.hibernate.po;
// Generated by MyEclipse - Hibernate Tools



/**
 * Fungradeconfig generated by MyEclipse - Hibernate Tools
 */
public class Fungradeconfig extends AbstractFungradeconfig implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Fungradeconfig() {
    }

	/** minimal constructor */
    public Fungradeconfig(Long fungradeconfigId) {
        super(fungradeconfigId);        
    }
    
    /** full constructor */
    public Fungradeconfig(Long fungradeconfigId, String fungradeconfigGradnode, Long fungradeconfigGradvalue) {
        super(fungradeconfigId, fungradeconfigGradnode, fungradeconfigGradvalue);        
    }
   
}
